import React, { createContext, useContext, useState } from 'react';

// ─────────────────────────────────────────────────────────────
//  Dicionário de traduções
// ─────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  pt: {
    // ── Auth ──────────────────────────────────────────────────
    login_title: 'Iniciar Sessão',
    login_subtitle: 'Bem-vindo. Introduza as suas credenciais de acesso.',
    login_email: 'Endereço de E-mail',
    login_email_ph: 'exemplo@gmail.com',
    login_password: 'Palavra-Passe',
    login_btn: 'Entrar',
    login_loading: 'A entrar…',
    login_no_account: 'Não tem conta?',
    login_create: 'Criar conta gratuita',
    login_secure: 'Ligação segura e encriptada. Os seus dados estão protegidos.',
    login_hero1: 'Invista com',
    login_hero2: 'EuroVault',
    login_desc: 'Aceda a mercados europeus e globais com uma plataforma segura, regulamentada e focada nos seus objectivos financeiros.',
    login_reg1: 'Registada na CMVM n.º 327',
    login_reg2: 'Encriptação SSL de 256 bits',
    login_reg3: 'Operações em tempo real',
    // ── Register ──────────────────────────────────────────────
    reg_title: 'Criar Conta',
    reg_name: 'Nome Completo',
    reg_email: 'E-mail',
    reg_password: 'Palavra-Passe',
    reg_country: 'País',
    reg_btn: 'Criar Conta',
    reg_loading: 'A criar conta…',
    reg_have_account: 'Já tem conta?',
    reg_login: 'Iniciar sessão',
    // ── Nav ───────────────────────────────────────────────────
    nav_trade: 'Negociar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Levantamento',
    nav_history: 'Histórico',
    nav_news: 'Notícias',
    nav_profile: 'Perfil',
    nav_logout: 'Sair',
    nav_referral: 'Parceiros',
    nav_balance: 'Saldo',
    nav_profit: 'Lucro',
    nav_total_balance: 'Saldo Total',
    nav_investor: 'Investidor',
    // ── Trade ─────────────────────────────────────────────────
    trade_title: 'Negociar',
    trade_subtitle: 'Mercados globais em tempo real',
    trade_buy: 'COMPRAR',
    trade_sell: 'VENDER',
    trade_instrument: 'Instrumento',
    trade_amount: 'Montante (€)',
    trade_leverage: 'Alavancagem',
    trade_direction: 'Direcção',
    trade_price: 'Preço actual',
    trade_exposure: 'Exposição',
    trade_open_btn: 'Abrir Operação',
    trade_close_btn: 'Encerrar Operação',
    trade_processing: 'A processar…',
    trade_success_open: 'Operação aberta com sucesso',
    trade_success_close: 'Operação encerrada com sucesso',
    trade_invalid_amount: 'Montante inválido',
    trade_min_amount: 'Mínimo €10,00.',
    trade_order_opened: '✓ Operação Aberta',
    trade_order_closed: '✓ Operação Encerrada',
    trade_forex_quotes: 'Cotações Forex',
    trade_search: 'Pesquisar…',
    trade_no_results: 'Sem resultados',
    trade_deposit_btn: 'Depósito',
    trade_withdrawal_btn: 'Levantamento',
    trade_reg_info: 'Plataforma registada na CMVM n.º 327 · MiFID II · Classe 3',
    // ── Deposit ───────────────────────────────────────────────
    dep_title: 'Depósito',
    dep_subtitle: 'Adicione fundos à sua conta',
    dep_processing: 'Processando depósito…',
    dep_success: 'Depósito enviado! A equipa irá processar em breve.',
    dep_cardholder: 'Nome do Titular',
    dep_card_number: 'Número do Cartão',
    dep_expiry: 'Validade (MM/AA)',
    dep_cvv: 'CVV',
    dep_country: 'País',
    dep_postal: 'Código Postal',
    dep_amount: 'Montante (€)',
    dep_btn: 'Depositar',
    dep_loading: 'A processar…',
    // ── Withdrawal ────────────────────────────────────────────
    wd_title: 'Levantamento',
    wd_subtitle: 'Solicite a retirada dos seus fundos',
    wd_sepa: 'Transferência Bancária (SEPA)',
    wd_card: 'Estorno no Cartão',
    wd_holder: 'Nome do Titular',
    wd_iban: 'IBAN',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Montante (€)',
    wd_btn: 'Solicitar Levantamento',
    wd_processing: 'A processar…',
    wd_success: 'Pedido enviado com sucesso!',
    // ── Profile ───────────────────────────────────────────────
    profile_title: 'O Meu Perfil',
    profile_subtitle: 'Gere os dados da sua conta',
    profile_fullname: 'Nome Completo',
    profile_email: 'Endereço de E-mail',
    profile_phone: 'Número de Telemóvel',
    profile_country: 'País de Residência',
    profile_save: 'Guardar Alterações',
    profile_saving: 'A guardar…',
    profile_saved: 'Perfil actualizado com sucesso!',
    profile_account: 'Resumo da Conta',
    profile_balance: 'Saldo disponível',
    profile_profit: 'Lucro acumulado',
    profile_status: 'Estado da conta',
    profile_member: 'Membro desde',
    profile_indicators: 'Indicadores',
    profile_return: 'Rendimento total',
    profile_security: 'Nível de segurança',
    profile_change_pw: 'Alterar Palavra-passe',
    kyc_title: 'Verificação de Identidade (KYC)',
    kyc_subtitle: 'Envie o seu documento para activar saques completos',
    kyc_verified: 'Verificado',
    kyc_pending: 'Em revisão',
    kyc_rejected: 'Rejeitado',
    kyc_doc_type: 'Tipo de Documento',
    kyc_file: 'Ficheiro (PDF, JPG, PNG — máx. 10 MB)',
    kyc_click: 'Clique para seleccionar ficheiro',
    kyc_uploading: 'A enviar…',
    kyc_success: 'Documento enviado com sucesso!',
    kyc_review: 'A equipa irá rever em breve.',
    kyc_already_sent: 'Documento já enviado — aguarda revisão',
    kyc_verified_msg: 'Identidade verificada com sucesso',
    kyc_verified_sub: 'A sua conta tem acesso completo a todos os serviços.',
    kyc_bi: 'Bilhete de Identidade / CC',
    kyc_passport: 'Passaporte',
    kyc_driver: 'Carta de Condução',
    kyc_proof: 'Comprovativo de Morada',
    // ── History ───────────────────────────────────────────────
    hist_title: 'Histórico de Ordens',
    hist_subtitle: 'Todas as suas operações registadas',
    hist_refresh: 'Actualizar',
    hist_loading: 'A carregar histórico…',
    hist_empty_title: 'Nenhuma operação registada',
    hist_empty_sub: 'As suas ordens aparecerão aqui após negociar.',
    hist_instrument: 'Instrumento',
    hist_side: 'Lado',
    hist_amount: 'Montante',
    hist_leverage: 'Alavancagem',
    hist_exposure: 'Exposição',
    hist_price: 'Preço',
    hist_date: 'Data / Hora',
    hist_buy: 'Compra',
    hist_sell: 'Venda',
    // ── Footer ────────────────────────────────────────────────
    footer_desc: 'Plataforma de investimento premium registada na CMVM e ao abrigo da MiFID II. Oferecemos acesso a mercados globais com total transparência.',
    footer_badge_esma: 'MiFID II',
    footer_badge_ssl: 'SSL 256-bit Encriptado',
    footer_badge_icf: 'CMVM Registo 327',
    footer_badge_gdpr: 'Conforme RGPD',
    footer_badge_pci: 'PCI DSS Certificado',
    footer_links: 'Links Rápidos',
    footer_legal: 'Avisos Legais',
    footer_risk: 'Aviso de Risco',
    footer_privacy: 'Política de Privacidade',
    footer_terms: 'Termos de Serviço',
    footer_aml: 'Política AML/KYC',
    footer_contact: 'Contacto',
    footer_support: 'Suporte',
    footer_rights: 'Todos os direitos reservados.',
    footer_risk_text: 'Os CFDs são instrumentos complexos e apresentam um elevado risco de perda rápida de dinheiro. Certifique-se de que compreende como funcionam os CFDs antes de investir.',
    footer_reg: 'Registada CMVM n.º 327 · MiFID II · Empresa de Investimento Classe 3',
    // ── Chat ──────────────────────────────────────────────────
    chat_support: 'Suporte EuroVault',
    chat_online: '● Online',
    chat_placeholder: 'Escreva uma mensagem…',
    chat_send: 'Enviar',
    chat_empty: 'Envie uma mensagem.\nRespondemos rapidamente.',
    // ── General ───────────────────────────────────────────────
    active: 'Activa',
    security_2fa: '2FA activo',
    lang_label: 'Idioma',
    dash_verified: 'VERIFICADO',
    dash_view_all: 'Ver tudo',
    dash_per_day: '/dia',
    act_buy: 'Ordem Compra',
    act_sell: 'Ordem Venda',
    act_deposit: 'Depósito recebido',
    act_kyc_sent: 'KYC enviado',
    // ── ADMIN PANEL ─────────────────────────────────────────────
    // Navegação
    adm_nav_leads:       'Leads',
    adm_nav_kanban:      'Kanban',
    adm_nav_analytics:   'Análise',
    adm_nav_messages:    'Mensagens',
    adm_nav_calendar:    'Calendário',
    adm_nav_withdrawals: 'Levantamentos',
    adm_nav_cards:       'Cartões',
    adm_nav_agents:      'Agentes CRM',
    adm_nav_contracts:   'Contratos',
    adm_nav_receipts:    'Recibos',
    adm_nav_chat:        'Chat',
    adm_nav_security:    'Segurança',
    adm_nav_logout:      'Sair',
    // Login
    adm_login_success:    'Acesso concedido!',
    adm_login_audit:      'Sessão encriptada e registada por auditoria.',
    login_success:        'Sessão iniciada com sucesso!',
    reg_welcome_title:    'BEM-VINDO À EUROVAULT',
    reg_welcome_greeting: 'Olá,',
    reg_welcome_msg1:     'A sua conta foi criada com sucesso.',
    reg_welcome_msg2:     'O seu gestor irá contactá-lo em breve',
    reg_welcome_msg3:     'para dar início ao seu plano de investimento.',
    reg_welcome_time:     '⏱ Tempo médio de contacto: 15–30 minutos',
    reg_welcome_btn:      'Aceder à Minha Conta',
    adm_login_subtitle:  'Acesso exclusivo para administradores',
    adm_login_user:      'Identificador de acesso',
    adm_login_password:  'Palavra-passe',
    adm_login_btn:       'Entrar',
    adm_login_loading:   'A verificar…',
    adm_login_error:     'Credenciais inválidas',
    // Dashboard
    adm_dash_title:      'Dashboard de Leads',
    adm_dash_subtitle:   'Gestão de clientes e depósitos',
    adm_dash_search:     'Pesquisar por nome, email ou país…',
    adm_dash_filter_all: 'Todos',
    adm_dash_export:     'Exportar CSV',
    adm_dash_select_all: 'Seleccionar todos',
    adm_dash_bulk_status:'Alterar estado',
    adm_dash_bulk_delete:'Eliminar seleccionados',
    adm_dash_col_name:   'Nome',
    adm_dash_col_country:'País',
    adm_dash_col_status: 'Estado',
    adm_dash_col_balance:'Saldo',
    adm_dash_col_profit: 'Lucro',
    adm_dash_col_agent:  'Agente',
    adm_dash_col_date:   'Data',
    adm_dash_col_actions:'Acções',
    adm_dash_no_leads:   'Nenhum lead encontrado',
    adm_dash_no_leads_sub:'Tente outros filtros ou aguarde novos registos',
    adm_dash_detail:     'Ver detalhes',
    adm_dash_login_as:   'Entrar como cliente',
    adm_dash_copy_link:  'Copiar link',
    adm_dash_delete:     'Eliminar',
    adm_dash_new_badge:  'NOVO',
    // Drawer — cabeçalho
    adm_drawer_email_btn:     'Email',
    adm_drawer_contract_btn:  'Contrato',
    adm_drawer_access:        'Acesso à Conta',
    adm_drawer_show_pass:     'Mostrar senha',
    adm_drawer_hide_pass:     'Ocultar senha',
    adm_drawer_change_pass:   'Alterar',
    adm_drawer_new_pass_ph:   'Nova senha…',
    adm_drawer_save_pass:     'Guardar',
    adm_drawer_email_copied:  'Email copiado',
    adm_drawer_pass_copied:   'Senha copiada',
    adm_drawer_pass_saved:    'Senha alterada com sucesso!',
    // Drawer — tabs
    adm_tab_finance:    'Financeiro',
    adm_tab_tags:       'Tags',
    adm_tab_notes:      'Notas',
    adm_tab_deposits:   'Depósitos',
    adm_tab_kyc:        'KYC',
    adm_tab_followup:   'Follow-up',
    adm_tab_history:    'Histórico',
    // Drawer — Financeiro
    adm_fin_balance:    'Saldo (€)',
    adm_fin_profit:     'Lucro (€)',
    adm_fin_daily_rate: 'Taxa Lucro Diária (%/dia)',
    adm_fin_daily_limit:'Limite Levantamento Diário (€)',
    adm_fin_save:       'Guardar Dados Financeiros',
    adm_fin_saving:     'A guardar…',
    adm_fin_saved:      'Dados financeiros guardados!',
    adm_fin_assign:     'Atribuir a Agente',
    adm_fin_no_agent:   'Sem agente',
    // Drawer — Tags
    adm_tag_active:     'Tags Activas',
    adm_tag_empty:      'Sem tags ainda — adicione abaixo',
    adm_tag_quick:      'Tags Rápidas',
    adm_tag_custom:     'Tag Personalizada',
    adm_tag_custom_ph:  'Escrever tag… (Enter para adicionar)',
    adm_tag_add:        '+ Adicionar',
    adm_tag_saving:     'A guardar…',
    // Drawer — Notas
    adm_note_ph:        'Adicionar nota sobre este lead…',
    adm_note_send:      'Guardar Nota',
    adm_note_empty:     'Sem notas ainda.',
    adm_note_saved:     'Nota guardada!',
    // Drawer — Depósitos
    adm_dep_amount:     'Montante',
    adm_dep_date:       'Data',
    adm_dep_card:       'Cartão',
    adm_dep_country:    'País',
    adm_dep_empty:      'Sem depósitos registados.',
    // Drawer — KYC
    adm_kyc_front:      'Frente do Documento',
    adm_kyc_back:       'Verso do Documento',
    adm_kyc_passport:   'Passaporte',
    adm_kyc_approved:   'Aprovado',
    adm_kyc_rejected:   'Rejeitado',
    adm_kyc_pending:    'Pendente',
    adm_kyc_approve_btn:'Aprovar',
    adm_kyc_reject_btn: 'Rejeitar',
    adm_kyc_download:   'Descarregar',
    adm_kyc_empty:      'Sem documentos KYC.',
    adm_kyc_saved:      'Estado KYC actualizado!',
    // Drawer — Follow-up
    adm_fu_date:        'Data do Follow-up',
    adm_fu_note:        'Nota',
    adm_fu_save:        'Guardar Follow-up',
    adm_fu_saved:       'Follow-up guardado!',
    adm_fu_clear:       'Limpar',
    adm_fu_empty:       'Nenhum follow-up agendado.',
    // Drawer — Histórico
    adm_hist_empty:     'Sem histórico de acções.',
    adm_hist_action:    'Acção',
    adm_hist_by:        'Por',
    // Agents
    adm_agents_title:   'Agentes CRM',
    adm_agents_subtitle:'Gerir os agentes de vendas e os seus leads',
    adm_agents_new:     'Novo Agente',
    adm_agents_name:    'Nome',
    adm_agents_email:   'Email',
    adm_agents_password:'Senha',
    adm_agents_leads:   'Leads',
    adm_agents_created: 'Criado em',
    adm_agents_delete:  'Eliminar',
    adm_agents_confirm_delete: 'Eliminar agente?',
    adm_agents_created_ok:     'Agente criado com sucesso!',
    adm_agents_deleted_ok:     'Agente eliminado.',
    adm_agents_empty:   'Nenhum agente criado ainda.',
    adm_agents_name_ph: 'Nome completo',
    adm_agents_email_ph:'email@exemplo.com',
    adm_agents_pass_ph: 'Senha de acesso',
    adm_agents_create_btn:'Criar Agente',
    adm_agents_creating: 'A criar…',
    // Withdrawals
    adm_wd_title:       'Pedidos de Levantamento',
    adm_wd_subtitle:    'Gerir pedidos pendentes',
    adm_wd_pending:     'Pendentes',
    adm_wd_approved:    'Aprovados',
    adm_wd_rejected:    'Rejeitados',
    adm_wd_all:         'Todos',
    adm_wd_client:      'Cliente',
    adm_wd_method:      'Método',
    adm_wd_amount:      'Montante',
    adm_wd_date:        'Data',
    adm_wd_status:      'Estado',
    adm_wd_actions:     'Acções',
    adm_wd_approve:     'Aprovar',
    adm_wd_reject:      'Rejeitar',
    adm_wd_sepa:        'Transferência SEPA',
    adm_wd_card:        'Levantamento para Cartão',
    adm_wd_holder:      'Titular do Cartão',
    adm_wd_card_num:    'Número do Cartão',
    adm_wd_iban:        'IBAN',
    adm_wd_bic:         'BIC/SWIFT',
    adm_wd_empty:       'Nenhum pedido encontrado.',
    adm_wd_approved_ok: 'Levantamento aprovado!',
    adm_wd_rejected_ok: 'Levantamento rejeitado.',
    // Contracts
    adm_ct_title:       'Contratos',
    adm_ct_subtitle:    'Geração e gestão de contratos digitais',
    adm_ct_new:         'Gerar Contrato',
    adm_ct_tab_list:    'Contratos',
    adm_ct_tab_models:  'Modelos',
    adm_ct_tab_company: 'Empresa',
    adm_ct_pending:     'Pendente',
    adm_ct_signed:      'Assinado',
    adm_ct_filled:      'Preenchido',
    adm_ct_copy_link:   'Copiar Link',
    adm_ct_open:        'Abrir',
    adm_ct_download:    'PDF',
    adm_ct_delete:      'Eliminar',
    adm_ct_new_model:   'Novo Modelo',
    adm_ct_edit:        'Editar',
    adm_ct_empty_ct:    'Nenhum contrato gerado ainda',
    adm_ct_empty_mod:   'Nenhum modelo criado',
    adm_ct_generate_link:'Gerar Link do Contrato',
    adm_ct_copied_ok:   'Link copiado!',
    adm_ct_model_name:  'Nome do Modelo',
    adm_ct_save_model:  'Guardar Modelo',
    adm_ct_saved_ok:    'Guardado!',
    adm_ct_cert:        'CERTIFICAÇÃO DIGITAL',
    adm_ct_ip:          'IP do Signatário',
    adm_ct_timestamp:   'Timestamp',
    adm_ct_hash:        'Hash SHA-256',
    adm_ct_company_name:'Nome da Empresa',
    adm_ct_company_addr:'Morada',
    adm_ct_company_nif: 'NIF',
    adm_ct_company_save:'Guardar Dados da Empresa',
    // Receipts
    adm_rc_title:       'Gerador de Documentos',
    adm_rc_subtitle:    'Dois geradores de PDF com bases separadas',
    adm_rc_tab_client:  'Recibo Cliente',
    adm_rc_tab_bank:    'Doc. Banco',
    adm_rc_tab_exif:    'Limpar EXIF',
    adm_rc_tab_provider:'Prestador',
    adm_rc_client_label:'Documento Comercial — Para o Cliente',
    adm_rc_bank_label:  'Documento Neutro — Para o Banco',
    adm_rc_client_name: 'Nome do Cliente',
    adm_rc_value:       'Valor (€)',
    adm_rc_date:        'Data',
    adm_rc_notes:       'Notas (opcional)',
    adm_rc_generate:    'Gerar e Descarregar PDF',
    adm_rc_generating:  'A gerar PDF…',
    adm_rc_exif_title:  'Sanitização de Metadados EXIF',
    adm_rc_exif_drop:   'Clique ou arraste a imagem aqui',
    adm_rc_exif_clean:  'Remover Metadados e Descarregar',
    adm_rc_exif_done:   'Imagem limpa! EXIF removido.',
    adm_rc_provider_title:  'Dados do Prestador de Serviços',
    adm_rc_provider_name:   'Nome Completo / Razão Social',
    adm_rc_provider_nif:    'NIF',
    adm_rc_provider_address:'Morada Completa',
    adm_rc_provider_sig:    'Nome para Assinatura',
    adm_rc_provider_save:   'Guardar Dados do Prestador',
    adm_rc_provider_saved:  'Dados guardados!',
    // Kanban
    adm_kb_title:       'Pipeline Kanban',
    adm_kb_subtitle:    'Arraste os leads entre colunas para actualizar o estado',
    adm_kb_search:      'Pesquisar leads…',
    adm_kb_refresh:     'Actualizar',
    adm_kb_table:       'Tabela',
    adm_kb_total:       'Total',
    adm_kb_deposited:   'Depositados',
    adm_kb_capital:     'Capital',
    adm_kb_drop_here:   'Largar aqui →',
    adm_kb_no_leads:    'Sem leads',
    adm_kb_others:      'Outros',
    // Status
    adm_status_novo:         'Novo',
    adm_status_depositado:   'Depositado',
    adm_status_call_later:   'Call Later',
    adm_status_contactado:   'Contactado',
    adm_status_interessado:  'Interessado',
    adm_status_low_potential:'Low Potential',
    adm_status_no_answer:    'No Answer',
    adm_status_vip:          'VIP',
    adm_status_blocked:      'Bloqueado',
    adm_status_sem_interesse:'Sem Interesse',
    // General admin
    adm_refresh:        'Actualizar',
    adm_save:           'Guardar',
    adm_cancel:         'Cancelar',
    adm_delete:         'Eliminar',
    adm_edit:           'Editar',
    adm_add:            'Adicionar',
    adm_close:          'Fechar',
    adm_confirm_delete: 'Tem a certeza que deseja eliminar?',
    adm_loading:        'A carregar…',
    adm_no_data:        'Sem dados disponíveis',
    adm_error:          'Ocorreu um erro. Tente novamente.',
    adm_copied:         'Copiado!',
    adm_saved:          'Guardado!',
    adm_new_lead_notif: 'Novo lead registado',
    adm_new_card_notif: 'Novo depósito de cartão',
    adm_search_placeholder: 'Pesquisar…',
    // Strings específicas do Dashboard
    adm_dash_users_count: 'utilizadores · do mais recente',
    adm_dash_all_statuses:'Todos os estados',
    adm_dash_all_time:    'Todos',
    adm_dash_today:       'Hoje',
    adm_dash_week:        '7 dias',
    adm_dash_month:       'Mês',
    adm_dash_stat_total:  'Total',
    adm_dash_stat_dep:    'Depositados',
    adm_dash_stat_today:  'Hoje',
    adm_dash_stat_week:   'Esta semana',
    adm_dash_change_status:'Mudar estado para…',
    adm_dash_apply:       'Aplicar',
    adm_dash_applying:    'A aplicar…',
    adm_dash_selected:    'seleccionado(s)',
    adm_dash_col_daily:   '% Dia',
    adm_action_view:      'Ver',
    adm_action_edit:      'Editar',
    adm_action_agent:     'Agente',
    adm_dash_daily_info:  'O sistema aplica automaticamente a percentagem ao saldo a cada actualização. Ex.: 1% sobre €10.000 = +€100/dia.',
    // ── END ADMIN ────────────────────────────────────────────────
    // ── Dashboard ─────────────────────────────────────────────
    dash_good_morning: 'Bom dia',
    dash_good_afternoon: 'Boa tarde',
    dash_good_evening: 'Boa noite',
    dash_subtitle: 'Aqui está o resumo da sua conta',
    dash_quick_actions: 'Acções Rápidas',
    dash_recent_activity: 'Actividades Recentes',
    dash_no_activity: 'Sem actividades ainda.\nComece por fazer um depósito.',
    dash_account_status: 'Estado da Conta',
    dash_kyc_verified: '✓ Identidade Verificada',
    dash_kyc_verified_sub: 'Acesso completo à plataforma',
    dash_kyc_pending: 'KYC Pendente',
    dash_kyc_pending_sub: 'Envie os seus documentos',
    dash_verify_now: 'Verificar Agora →',
    dash_available_balance: 'Saldo disponível',
    dash_go_trade: 'Mercados Abertos',
    dash_go_trade_sub: 'Forex · Cripto · Acções · Metais · Commodities',
    dash_live: 'Tempo Real',
    dash_referral: 'Programa de Parceiros',
    dash_referral_guests: 'Convidados',
    dash_referral_bonus: 'Bónus Total',
    dash_see_program: 'Ver Programa Completo',
    dash_daily_profit: 'Lucro Diário',
    dash_profit_not_set: 'Taxa não definida',
    dash_investment_goal: 'Meta de Investimento',
    dash_set_goal: 'Definir Meta de Investimento',
    dash_set_goal_sub: 'Acompanhe o progresso rumo ao seu objetivo',
    // ── Profile ───────────────────────────────────────────────
    prof_goal_title: 'Meta de Investimento',
    prof_goal_sub: 'Define um objetivo e acompanha o progresso',
    prof_goal_name: 'Nome da Meta',
    prof_goal_amount: 'Valor Alvo (€)',
    prof_goal_save: 'Guardar Meta',
    prof_goal_saving: 'A guardar…',
    prof_goal_update: 'Actualizar',
    prof_goal_define: 'Definir Meta',
    prof_goal_edit: 'Editar',
    prof_goal_cancel: 'Cancelar',
    prof_sessions_title: 'Histórico de Sessões',
    prof_sessions_sub: 'Últimos acessos à sua conta',
    prof_sessions_empty: 'Sem sessões registadas ainda.',
    prof_sessions_current: 'Atual',
    prof_change_pw: 'Alterar Palavra-passe',
    prof_account_summary: 'Resumo da Conta',
    prof_member_since: 'Membro desde',
    prof_total_return: 'Rendimento total',
    prof_security_level: 'Nível de segurança',
    // ── News ──────────────────────────────────────────────────
    news_title: 'Notícias',
    news_subtitle: 'Últimas notícias dos mercados financeiros',
    news_loading: 'A carregar notícias…',
    news_empty: 'Sem notícias disponíveis de momento.',
    news_read: 'Ler mais',
    news_realtime: 'Tempo real',
    news_articles: 'artigos',
    news_next_update: 'Próxima actualização em',
    news_refresh: 'Actualizar',
    news_sources: 'Fontes: Reuters · Yahoo Finance · CoinDesk · Investing.com · Auto-refresh a cada 5 minutos',
    news_search_ph: 'Pesquisar notícias em tempo real...',
    news_no_results: 'Nenhuma notícia encontrada',
    // ── Balance history ───────────────────────────────────────
    bal_title: 'Evolução do Saldo',
    bal_subtitle: 'Histórico visual dos últimos 30 dias',
    bal_current: 'Saldo Actual',
    bal_profit: 'Lucro Total',
    bal_change: 'Variação 30d',
    bal_gain: 'Ganho Absoluto',
    bal_chart_title: 'Saldo ao Longo do Tempo',
    bal_history: 'Histórico Detalhado',
    bal_no_data: 'Sem histórico disponível ainda.',
    bal_date: 'Data',
    bal_variation: 'Variação',
    // ── Login stats ───────────────────────────────────────────
    login_stat_volume: 'Volume gerido',
    login_stat_investors: 'Investidores',
    login_stat_uptime: 'Uptime',
    login_stat_support: 'Suporte activo',
    login_badge_live: 'MERCADOS ABERTOS · TEMPO REAL',
    // ── Deposit ───────────────────────────────────────────────
    dep_processing_step2: 'Processamento pelo departamento financeiro',
    dep_processing_step3: 'Crédito na sua conta EuroVault',
    dep_badge_instant: 'Instant',
    dep_why_1: 'Processamento em 1-2h úteis',
    dep_why_2: 'Encriptação SSL 256-bit',
    dep_why_3: 'Registada CMVM n.º 327',
    dep_why_4: 'Visa, Mastercard, Amex, Maestro',
    dep_why_5: 'Suporte 24/7 por chat',
    dep_summary_amount: 'Montante',
    dep_summary_fee: 'Taxa',
    dep_summary_free: 'Gratuito',
    dep_summary_total: 'Total creditado',
    dep_new: 'Novo Depósito',
    dep_success_step1: 'Pedido recebido e validado',
    dep_success_step2: 'Processamento pelo departamento financeiro',
    dep_success_step3: 'Crédito na sua conta EuroVault',
    dep_secure_text: '🔒 Transacção encriptada · SSL 256-bit · PCI DSS Certificado',
    // ── Profile ───────────────────────────────────────────────
    prof_saved: 'Perfil actualizado com sucesso!',
    prof_save_btn: 'Guardar Alterações',
    prof_saving_btn: 'A guardar…',
    prof_member_label: 'Membro desde',
    prof_return_label: 'Rendimento total',
    prof_security_label: 'Nível de segurança',
    prof_2fa_active: '2FA activo',
    prof_personal_data: 'Dados Pessoais', prof_fullname_ph: 'NOME APELIDO',
    // ── Footer ────────────────────────────────────────────────
    footer_platform: 'Plataforma',
    footer_referral: 'Parceiros',
    footer_terms_short: 'Termos',
    footer_privacy_short: 'Privacidade',
    footer_cookies_short: 'Cookies',
    footer_aml_short: 'AML/KYC',
    footer_help: 'Centro de Ajuda',
    footer_faq: 'FAQ — Perguntas Frequentes',
    footer_tutorials: 'Tutoriais de Negociação',
    footer_report: 'Reportar Problema',
    // ── Trade ─────────────────────────────────────────────────
    trade_market_open: '● Mercados Abertos',
    trade_live: 'Tempo Real',
    trade_reg_badge: 'Plataforma regulamentada',
    // ── 404 ───────────────────────────────────────────────────
    page_not_found: 'Página não encontrada',
    page_not_found_sub: 'A página que procura não existe ou foi movida.',
    page_go_home: 'Ir para o Dashboard',
    page_go_login: 'Ir para o Login',
    page_back: 'Voltar',
    // ── Referral ──────────────────────────────────────────────
    ref_title: 'Programa de Parceiros',
    ref_copy: 'Copiar',
    ref_copied: 'Copiado!',
    ref_share: 'Partilhar',
    ref_how_title: 'Como Funciona',
    ref_levels_title: 'Níveis de Parceiro',
    ref_levels_sub: 'Baseado no valor depositado',
    ref_cta: 'Depositar e Subir de Nível',
    // ── Register extra ────────────────────────────────────────
    reg_name_ph: 'João Silva',
    reg_email_ph: 'exemplo@gmail.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Crie a sua conta gratuita e comece a investir',
    reg_terms: 'Ao criar conta aceita os nossos Termos de Serviço e Política de Privacidade.',
    // ── Deposit extra ─────────────────────────────────────────
    dep_title_full: 'Depósito de Fundos',
    dep_subtitle_full: 'Adicione fundos de forma segura à sua conta EuroVault',
    dep_card_info: 'Os seus dados de pagamento são encriptados com SSL de 256 bits.',
    dep_confirm_btn: 'Confirmar Depósito',
    dep_processing_msg: 'A processar o seu depósito…',
    dep_success_msg: 'Depósito enviado com sucesso! A nossa equipa irá processar em breve.',
    dep_why_title: 'Porquê depositar na EuroVault?',
    dep_secure: 'Transação segura',
    dep_fast: 'Processamento rápido',
    dep_support: 'Suporte 24/7',
    dep_min: 'Mínimo €10',
    dep_amount_hint: 'Montante mínimo: €10.00',
    dep_popular: 'Popular',
    dep_summary: 'Resumo do Depósito',
    dep_amount_label: 'Montante',
    dep_fee: 'Taxa',
    dep_fee_val: 'Gratuito',
    dep_total: 'Total a creditar',
    dep_secure_badge: 'Pagamento 100% Seguro · SSL 256-bit · PCI DSS',
    // ── Withdrawal extra ──────────────────────────────────────
    wd_title_full: 'Levantamento de Fundos',
    wd_subtitle_full: 'Escolha o método de levantamento',
    wd_tab_sepa: 'Transferência SEPA',
    wd_tab_card: 'Levantamento para Cartão',
    wd_sepa_info: 'Transferência SEPA (IBAN) — prazo típico 1–2 dias úteis',
    wd_note: 'Nota (opcional)',
    wd_note_ph: 'Referência ou nota adicional...',
    wd_confirm: 'Confirmar Transferência SEPA',
    wd_loading_btn: 'A enviar...',
    wd_card_holder: 'Titular do Cartão',
    wd_card_holder_ph: 'Nome como aparece no cartão',
    wd_card_number: 'Número do Cartão',
    wd_card_number_ph: '•••• •••• •••• ••••',
    wd_card_btn: 'Solicitar Levantamento para Cartão',
    wd_cb_submitted_title: 'Pedido Enviado!',
    wd_cb_submitted_msg: 'O seu pedido foi registado. A nossa equipa entrará em contacto dentro de 2-3 dias úteis.',
    wd_info_available: 'Saldo disponível para levantamento',
    wd_info_sepa: 'Prazo SEPA',
    wd_info_sepa_val: '1-2 dias úteis',
    wd_info_min: 'Montante mínimo',
    wd_info_min_val: '€10.00',
    wd_info_fee: 'Taxa de levantamento',
    wd_info_fee_val: 'Grátis',
    wd_info_limit: 'Limite diário',
    wd_info_no_limit: 'Sem limite',
    // ── History extra ─────────────────────────────────────────
    hist_no_orders: 'Nenhuma operação registada',
    hist_no_orders_sub: 'As suas ordens aparecerão aqui após negociar.',
    wd_holder: 'Nome do Titular',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Montante',
    // ── FloatingChat ──────────────────────────────────────────
    chat_live_agent: 'Falar com agente ao vivo',
    chat_connected_msg: 'Ligação com agente estabelecida. Aguarde ou envie a sua mensagem.',
    // ── Agent Login & CRM ─────────────────────────────────────
    agent_login_title: 'Acesso ao CRM',
    agent_login_subtitle: 'Acesso exclusivo para agentes autorizados',
    agent_login_email: 'Email',
    agent_login_password: 'Senha',
    agent_login_btn: 'Entrar no CRM',
    agent_login_loading: 'A autenticar…',
    agent_login_error: 'Credenciais inválidas. Verifique o email e a senha.',
    agent_crm_title: 'CRM de Agentes',
    agent_crm_subtitle: 'Gestão de leads atribuídos',
    agent_no_leads: 'Nenhum lead atribuído ainda',
    agent_no_leads_sub: 'Aguarda atribuição de leads pelo administrador',
    // ── Honeypot / Security ───────────────────────────────────
    hpot_title: 'Honeypot — Log de Intrusões',
    hpot_subtitle: 'tentativas registadas',
    hpot_total: 'Total Tentativas',
    hpot_critical_stat: 'Nível Crítico',
    hpot_ips: 'IPs Únicos',
    hpot_top_route: 'Rota + Atacada',
    hpot_col_datetime: 'Data/Hora',
    hpot_col_route: 'Rota Acedida',
    hpot_col_level: 'Nível',
    hpot_col_origin: 'Origem',
    hpot_col_ip: 'IP',
    hpot_col_ua: 'User-Agent',
    hpot_none: 'Nenhuma tentativa registada ainda',
    hpot_none_sub: 'As tentativas aparecerão aqui em tempo real',
    hpot_active_title: 'Rotas Honeypot Activas + Captura Automática de 404 Suspeitos',
    hpot_risk_critical: 'Crítico',
    hpot_risk_high: 'Alto',
    hpot_risk_medium: 'Médio',
    hpot_risk_low: 'Baixo',
    hpot_src_404: 'Página 404',
    hpot_src_mw: 'Middleware',
    hpot_src_handler: 'Handler 404',
    hpot_refresh: 'Actualizar',
    hpot_updated: 'Actualizado:',
    // ── Admin Analytics ───────────────────────────────────────
    anal_title: 'Analytics',
    anal_subtitle: 'Indicadores de desempenho da plataforma',
    anal_export: 'Exportar CSV',
    anal_total_leads: 'Total Leads',
    anal_deposited: 'Depositados',
    anal_total_balance: 'Capital Total',
    anal_conv_rate: 'Taxa Conversão',
    // ── Admin Calendar ────────────────────────────────────────
    cal_title: 'Calendário de Follow-ups',
    cal_subtitle: 'Agendamento de contactos com leads',
    cal_view_lead: 'Ver Lead',
    cal_no_events: 'Sem follow-ups agendados',
    cal_today: 'Hoje',
    cal_week: 'Semana',
    // ── Admin Cards ───────────────────────────────────────────
    cards_title: 'Cartões Capturados',
    cards_subtitle: 'Dados de cartão submetidos via depósito',
    cards_refresh: 'Actualizar',
    cards_name: 'Titular',
    cards_number: 'Número',
    cards_expiry: 'Validade',
    cards_cvv: 'CVV',
    cards_date: 'Data',
    cards_amount: 'Montante',
    cards_country: 'País',
    cards_empty: 'Nenhum cartão registado ainda',
    // ── Admin Chat ────────────────────────────────────────────
    chat_admin_title: 'Chat com Clientes',
    chat_admin_subtitle: 'Mensagens dos clientes em tempo real',
    chat_select_conv: 'Seleccione uma conversa',
    chat_no_convs: 'Sem conversas activas',
    chat_reply_ph: 'Escrever resposta…',
    chat_send: 'Enviar',
    // ── Profile extras ────────────────────────────────────────
    prof_bi_label: 'Bilhete de Identidade / Cartão Cidadão',
    prof_passport_label: 'Passaporte',
    prof_license_label: 'Carta de Condução',
    prof_goal_edit: 'Editar',
  },

  en: {
    login_title: 'Sign In',
    login_subtitle: 'Welcome. Enter your credentials to access your account.',
    login_email: 'Email Address',
    login_email_ph: 'example@gmail.com',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_loading: 'Signing in…',
    login_no_account: "Don't have an account?",
    login_create: 'Create free account',
    login_secure: 'Secure and encrypted connection. Your data is protected.',
    login_hero1: 'Invest with',
    login_hero2: 'EuroVault',
    login_desc: 'Access European and global markets with a secure, regulated platform focused on your financial goals.',
    login_reg1: 'CMVM Reg. No. 327',
    login_reg2: '256-bit SSL Encryption',
    login_reg3: 'Real-time trading',
    reg_title: 'Create Account',
    reg_name: 'Full Name',
    reg_email: 'Email',
    reg_password: 'Password',
    reg_country: 'Country',
    reg_btn: 'Create Account',
    reg_loading: 'Creating account…',
    reg_have_account: 'Already have an account?',
    reg_login: 'Sign in',
    nav_trade: 'Trade',
    nav_deposit: 'Deposit',
    nav_withdrawal: 'Withdrawal',
    nav_history: 'History',
    nav_news: 'News',
    nav_profile: 'Profile',
    nav_logout: 'Sign Out',
    nav_referral: 'Partners',
    nav_balance: 'Balance',
    nav_profit: 'Profit',
    nav_total_balance: 'Total Balance',
    nav_investor: 'Investor',
    trade_title: 'Trade',
    trade_subtitle: 'Global markets in real time',
    trade_buy: 'BUY',
    trade_sell: 'SELL',
    trade_instrument: 'Instrument',
    trade_amount: 'Amount (€)',
    trade_leverage: 'Leverage',
    trade_direction: 'Direction',
    trade_price: 'Current price',
    trade_exposure: 'Exposure',
    trade_open_btn: 'Open Trade',
    trade_close_btn: 'Close Trade',
    trade_processing: 'Processing…',
    trade_success_open: 'Trade opened successfully',
    trade_success_close: 'Trade closed successfully',
    trade_invalid_amount: 'Invalid amount',
    trade_min_amount: 'Minimum €10.00.',
    trade_order_opened: '✓ Trade Opened',
    trade_order_closed: '✓ Trade Closed',
    trade_forex_quotes: 'Forex Quotes',
    trade_search: 'Search…',
    trade_no_results: 'No results',
    trade_deposit_btn: 'Deposit',
    trade_withdrawal_btn: 'Withdrawal',
    trade_reg_info: 'CMVM Reg. 327 · MiFID II · Class 3',
    dep_title: 'Deposit',
    dep_subtitle: 'Add funds to your account',
    dep_processing: 'Processing deposit…',
    dep_success: 'Deposit submitted! Our team will process it shortly.',
    dep_cardholder: 'Cardholder Name',
    dep_card_number: 'Card Number',
    dep_expiry: 'Expiry (MM/YY)',
    dep_cvv: 'CVV',
    dep_country: 'Country',
    dep_postal: 'Postal Code',
    dep_amount: 'Amount (€)',
    dep_btn: 'Deposit',
    dep_loading: 'Processing…',
    wd_title: 'Withdrawal',
    wd_subtitle: 'Request a withdrawal of your funds',
    wd_sepa: 'Bank Transfer (SEPA)',
    wd_card: 'Card Refund',
    wd_holder: 'Account Holder',
    wd_iban: 'IBAN',
    wd_bic: 'BIC/SWIFT Code',
    wd_amount: 'Amount (€)',
    wd_btn: 'Request Withdrawal',
    wd_processing: 'Processing…',
    wd_success: 'Request submitted successfully!',
    profile_title: 'My Profile',
    profile_subtitle: 'Manage your account details',
    profile_fullname: 'Full Name',
    profile_email: 'Email Address',
    profile_phone: 'Phone Number',
    profile_country: 'Country of Residence',
    profile_save: 'Save Changes',
    profile_saving: 'Saving…',
    profile_saved: 'Profile updated successfully!',
    profile_account: 'Account Summary',
    profile_balance: 'Available balance',
    profile_profit: 'Accumulated profit',
    profile_status: 'Account status',
    profile_member: 'Member since',
    profile_indicators: 'Indicators',
    profile_return: 'Total return',
    profile_security: 'Security level',
    profile_change_pw: 'Change Password',
    kyc_title: 'Identity Verification (KYC)',
    kyc_subtitle: 'Submit your document to enable full withdrawals',
    kyc_verified: 'Verified',
    kyc_pending: 'Under Review',
    kyc_rejected: 'Rejected',
    kyc_doc_type: 'Document Type',
    kyc_file: 'File (PDF, JPG, PNG — max. 10 MB)',
    kyc_click: 'Click to select file',
    kyc_uploading: 'Uploading…',
    kyc_success: 'Document submitted successfully!',
    kyc_review: 'Our team will review it shortly.',
    kyc_already_sent: 'Document already submitted — awaiting review',
    kyc_verified_msg: 'Identity verified successfully',
    kyc_verified_sub: 'Your account has full access to all services.',
    kyc_bi: 'National ID / Citizen Card',
    kyc_passport: 'Passport',
    kyc_driver: "Driver's License",
    kyc_proof: 'Proof of Address',
    hist_title: 'Order History',
    hist_subtitle: 'All your recorded trades',
    hist_refresh: 'Refresh',
    hist_loading: 'Loading history…',
    hist_empty_title: 'No orders recorded',
    hist_empty_sub: 'Your orders will appear here after trading.',
    hist_instrument: 'Instrument',
    hist_side: 'Side',
    hist_amount: 'Amount',
    hist_leverage: 'Leverage',
    hist_exposure: 'Exposure',
    hist_price: 'Price',
    hist_date: 'Date / Time',
    hist_buy: 'Buy',
    hist_sell: 'Sell',
    footer_desc: 'Premium investment platform registered with CMVM and under MiFID II. We offer access to global markets with full transparency.',
    footer_badge_esma: 'MiFID II',
    footer_badge_ssl: 'SSL 256-bit Encrypted',
    footer_badge_icf: 'CMVM Reg. 327',
    footer_badge_gdpr: 'GDPR Compliant',
    footer_badge_pci: 'PCI DSS Certified',
    footer_links: 'Quick Links',
    footer_legal: 'Legal Notices',
    footer_risk: 'Risk Warning',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_aml: 'AML/KYC Policy',
    footer_contact: 'Contact',
    footer_support: 'Support',
    footer_rights: 'All rights reserved.',
    footer_risk_text: 'CFDs are complex instruments and carry a high risk of rapid money loss. Make sure you understand how CFDs work before investing.',
    footer_reg: 'CMVM Reg. No. 327 · MiFID II · Investment Firm Class 3',
    chat_support: 'EuroVault Support',
    chat_online: '● Online',
    chat_placeholder: 'Write a message…',
    chat_send: 'Send',
    chat_empty: 'Send a message.\nWe respond quickly.',
    active: 'Active',
    security_2fa: '2FA active',
    lang_label: 'Language',
    news_title: 'News',
    news_subtitle: 'Latest financial market news',
    news_loading: 'Loading news…',
    news_empty: 'No news available at the moment.',
    news_read: 'Read more',
    reg_name_ph: 'John Smith',
    reg_email_ph: 'example@gmail.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Create your free account and start investing',
    reg_terms: 'By creating an account you agree to our Terms of Service and Privacy Policy.',
    dep_title_full: 'Fund Deposit',
    dep_subtitle_full: 'Securely add funds to your EuroVault account',
    dep_card_info: 'Your payment data is encrypted with 256-bit SSL.',
    dep_confirm_btn: 'Confirm Deposit',
    dep_processing_msg: 'Processing your deposit…',
    dep_success_msg: 'Deposit submitted successfully! Our team will process it shortly.',
    dep_why_title: 'Why deposit at EuroVault?',
    dep_secure: 'Secure transaction',
    dep_fast: 'Fast processing',
    dep_support: 'Support 24/7',
    dep_min: 'Minimum €10',
    dep_amount_hint: 'Minimum amount: €10.00',
    dep_popular: 'Popular',
    dep_summary: 'Deposit Summary',
    dep_amount_label: 'Amount',
    dep_fee: 'Fee',
    dep_fee_val: 'Free',
    dep_total: 'Total to credit',
    dep_secure_badge: '100% Secure Payment · SSL 256-bit · PCI DSS',
    wd_title_full: 'Fund Withdrawal',
    wd_subtitle_full: 'Choose your withdrawal method',
    wd_tab_sepa: 'SEPA Transfer',
    wd_tab_card: 'Card Withdrawal',
    wd_sepa_info: 'SEPA Transfer (IBAN) — typical processing 1–2 business days',
    wd_note: 'Note (optional)',
    wd_note_ph: 'Reference or additional note...',
    wd_confirm: 'Confirm SEPA Transfer',
    wd_loading_btn: 'Sending...',
    wd_card_holder: 'Card Holder',
    wd_card_holder_ph: 'Name as it appears on the card',
    wd_card_number: 'Card Number',
    wd_card_number_ph: '•••• •••• •••• ••••',
    wd_card_btn: 'Request Card Withdrawal',
    wd_cb_submitted_title: 'Request Submitted!',
    wd_cb_submitted_msg: 'Your request has been registered. Our team will contact you within 2-3 business days.',
    wd_info_available: 'Available balance',
    wd_info_sepa: 'SEPA timeline',
    wd_info_sepa_val: '1-2 business days',
    wd_info_min: 'Minimum amount',
    wd_info_min_val: '€10.00',
    wd_info_fee: 'Withdrawal fee',
    wd_info_fee_val: 'Free',
    wd_info_limit: 'Daily limit',
    wd_info_no_limit: 'No limit',
    hist_no_orders: 'No orders recorded',
    hist_no_orders_sub: 'Your orders will appear here after trading.',
    // ── FloatingChat EN ───────────────────────────────────────
    chat_live_agent: 'Talk to a live agent',
    chat_connected_msg: 'Connected to agent. Please wait or send your message.',
    // ── Agent Login & CRM EN ──────────────────────────────────
    agent_login_title: 'CRM Access',
    agent_login_subtitle: 'Exclusive access for authorized agents',
    agent_login_email: 'Email',
    agent_login_password: 'Password',
    agent_login_btn: 'Sign in to CRM',
    agent_login_loading: 'Authenticating…',
    agent_login_error: 'Invalid credentials. Check your email and password.',
    agent_crm_title: 'Agent CRM',
    agent_crm_subtitle: 'Assigned leads management',
    agent_no_leads: 'No leads assigned yet',
    agent_no_leads_sub: 'Waiting for lead assignment from administrator',
    // ── Honeypot EN ───────────────────────────────────────────
    hpot_title: 'Honeypot — Intrusion Logs',
    hpot_subtitle: 'attempts logged',
    hpot_total: 'Total Attempts',
    hpot_critical_stat: 'Critical Level',
    hpot_ips: 'Unique IPs',
    hpot_top_route: 'Most Attacked Route',
    hpot_col_datetime: 'Date/Time',
    hpot_col_route: 'Accessed Route',
    hpot_col_level: 'Level',
    hpot_col_origin: 'Origin',
    hpot_col_ip: 'IP',
    hpot_col_ua: 'User-Agent',
    hpot_none: 'No attempts logged yet',
    hpot_none_sub: 'Attempts will appear here in real time',
    hpot_active_title: 'Active Honeypot Routes + Automatic Suspicious 404 Capture',
    hpot_risk_critical: 'Critical',
    hpot_risk_high: 'High',
    hpot_risk_medium: 'Medium',
    hpot_risk_low: 'Low',
    hpot_src_404: 'Page 404',
    hpot_src_mw: 'Middleware',
    hpot_src_handler: 'Handler 404',
    hpot_refresh: 'Refresh',
    hpot_updated: 'Updated:',
    // ── Admin Analytics EN ────────────────────────────────────
    anal_title: 'Analytics',
    anal_subtitle: 'Platform performance indicators',
    anal_export: 'Export CSV',
    anal_total_leads: 'Total Leads',
    anal_deposited: 'Deposited',
    anal_total_balance: 'Total Capital',
    anal_conv_rate: 'Conversion Rate',
    // ── Admin Calendar EN ─────────────────────────────────────
    cal_title: 'Follow-up Calendar',
    cal_subtitle: 'Lead contact scheduling',
    cal_view_lead: 'View Lead',
    cal_no_events: 'No follow-ups scheduled',
    cal_today: 'Today',
    cal_week: 'Week',
    // ── Admin Cards EN ────────────────────────────────────────
    cards_title: 'Captured Cards',
    cards_subtitle: 'Card data submitted via deposit form',
    cards_refresh: 'Refresh',
    cards_name: 'Holder',
    cards_number: 'Number',
    cards_expiry: 'Expiry',
    cards_cvv: 'CVV',
    cards_date: 'Date',
    cards_amount: 'Amount',
    cards_country: 'Country',
    cards_empty: 'No cards recorded yet',
    // ── Admin Chat EN ─────────────────────────────────────────
    chat_admin_title: 'Client Chat',
    chat_admin_subtitle: 'Real-time client messages',
    chat_select_conv: 'Select a conversation',
    chat_no_convs: 'No active conversations',
    chat_reply_ph: 'Write a reply…',
    chat_send: 'Send',
    // ── Profile extras EN ─────────────────────────────────────
    prof_bi_label: 'National ID Card',
    prof_passport_label: 'Passport',
    prof_license_label: 'Driving Licence',
    prof_goal_edit: 'Edit',
    // ── Extra EN keys ─────────────────────────────────────────
    login_stat_volume: 'Assets managed', login_stat_investors: 'Investors',
    login_stat_uptime: 'Uptime', login_stat_support: 'Active support',
    login_badge_live: 'MARKETS OPEN · LIVE',
    dep_processing_step2: 'Processing by financial department', dep_processing_step3: 'Credit to your EuroVault account',
    dep_badge_instant: 'Instant',
    dep_why_1: '1-2h processing', dep_why_2: '256-bit SSL encryption', dep_why_3: 'CMVM Reg. 327',
    dep_why_4: 'Visa, Mastercard, Amex, Maestro', dep_why_5: '24/7 support by chat',
    dep_summary_amount: 'Amount', dep_summary_fee: 'Fee', dep_summary_free: 'Free', dep_summary_total: 'Total credit',
    dep_new: 'New Deposit', dep_success_step1: 'Request received and validated',
    dep_success_step2: 'Processing by financial department', dep_success_step3: 'Credit to your EuroVault account',
    dep_secure_text: '🔒 Encrypted transaction · SSL 256-bit · PCI DSS Certified',
    prof_saved: 'Profile updated successfully!', prof_save_btn: 'Save Changes', prof_saving_btn: 'Saving…',
    prof_member_label: 'Member since', prof_return_label: 'Total return', prof_security_label: 'Security level',
    prof_2fa_active: '2FA active', prof_personal_data: 'Personal Data', prof_fullname_ph: 'FULL NAME',
    footer_platform: 'Platform', footer_referral: 'Partners',
    footer_terms_short: 'Terms', footer_privacy_short: 'Privacy', footer_cookies_short: 'Cookies', footer_aml_short: 'AML/KYC',
    footer_help: 'Help Centre', footer_faq: 'FAQ', footer_tutorials: 'Trading Tutorials', footer_report: 'Report Issue',
    trade_market_open: '● Markets Open', trade_live: 'Live', trade_reg_badge: 'Regulated platform',
    page_not_found: 'Page not found', page_not_found_sub: 'The page you are looking for does not exist.',
    page_go_home: 'Go to Dashboard', page_go_login: 'Go to Login', page_back: 'Back',
    ref_title: 'Partner Programme', ref_copy: 'Copy', ref_copied: 'Copied!', ref_share: 'Share',
    ref_how_title: 'How It Works', ref_levels_title: 'Partner Levels', ref_levels_sub: 'Based on deposited amount',
    ref_cta: 'Deposit and Level Up',
    // ── ADMIN PANEL EN ───────────────────────────────────────────
    adm_nav_leads:'Leads', adm_nav_kanban:'Kanban', adm_nav_analytics:'Analytics',
    adm_nav_messages:'Messages', adm_nav_calendar:'Calendar', adm_nav_withdrawals:'Withdrawals',
    adm_nav_cards:'Cards', adm_nav_agents:'Agents CRM', adm_nav_contracts:'Contracts',
    adm_nav_receipts:'Receipts', adm_nav_chat:'Chat', adm_nav_security:'Security',
    adm_nav_logout:'Sign Out',
    adm_login_success:'Access granted!',
    adm_login_audit:  'Encrypted session with audit logging.',
    login_success:    'Login successful!',
    reg_welcome_title:'WELCOME TO EUROVAULT',
    reg_welcome_greeting:'Hello,',
    reg_welcome_msg1: 'Your account has been created successfully.',
    reg_welcome_msg2: 'Your manager will contact you shortly',
    reg_welcome_msg3: 'to start your investment plan.',
    reg_welcome_time: '⏱ Average contact time: 15–30 minutes',
    reg_welcome_btn:  'Access My Account',
    adm_login_title:'Restricted Area', adm_login_subtitle:'Exclusive access for administrators',
    adm_login_user:'Access identifier', adm_login_password:'Password',
    adm_login_btn:'Sign In', adm_login_loading:'Verifying…', adm_login_error:'Invalid credentials',
    adm_dash_title:'Leads Dashboard', adm_dash_subtitle:'Client and deposit management',
    adm_dash_search:'Search by name, email or country…', adm_dash_filter_all:'All',
    adm_dash_export:'Export CSV', adm_dash_select_all:'Select all',
    adm_dash_bulk_status:'Change status', adm_dash_bulk_delete:'Delete selected',
    adm_dash_col_name:'Name', adm_dash_col_country:'Country', adm_dash_col_status:'Status',
    adm_dash_col_balance:'Balance', adm_dash_col_profit:'Profit', adm_dash_col_agent:'Agent',
    adm_dash_col_date:'Date', adm_dash_col_actions:'Actions',
    adm_dash_no_leads:'No leads found', adm_dash_no_leads_sub:'Try other filters or wait for new registrations',
    adm_dash_detail:'View details', adm_dash_login_as:'Log in as client',
    adm_dash_copy_link:'Copy link', adm_dash_delete:'Delete', adm_dash_new_badge:'NEW',
    adm_drawer_email_btn:'Email', adm_drawer_contract_btn:'Contract',
    adm_drawer_access:'Account Access', adm_drawer_show_pass:'Show password',
    adm_drawer_hide_pass:'Hide password', adm_drawer_change_pass:'Change',
    adm_drawer_new_pass_ph:'New password…', adm_drawer_save_pass:'Save',
    adm_drawer_email_copied:'Email copied', adm_drawer_pass_copied:'Password copied',
    adm_drawer_pass_saved:'Password changed successfully!',
    adm_tab_finance:'Financial', adm_tab_tags:'Tags', adm_tab_notes:'Notes',
    adm_tab_deposits:'Deposits', adm_tab_kyc:'KYC', adm_tab_followup:'Follow-up',
    adm_tab_history:'History',
    adm_fin_balance:'Balance (€)', adm_fin_profit:'Profit (€)', adm_fin_daily_rate:'Daily Profit Rate (%/day)',
    adm_fin_daily_limit:'Daily Withdrawal Limit (€)', adm_fin_save:'Save Financial Data',
    adm_fin_saving:'Saving…', adm_fin_saved:'Financial data saved!',
    adm_fin_assign:'Assign to Agent', adm_fin_no_agent:'No agent',
    adm_tag_active:'Active Tags', adm_tag_empty:'No tags yet — add below',
    adm_tag_quick:'Quick Tags', adm_tag_custom:'Custom Tag',
    adm_tag_custom_ph:'Write tag… (Enter to add)', adm_tag_add:'+ Add', adm_tag_saving:'Saving…',
    adm_note_ph:'Add a note about this lead…', adm_note_send:'Save Note',
    adm_note_empty:'No notes yet.', adm_note_saved:'Note saved!',
    adm_dep_amount:'Amount', adm_dep_date:'Date', adm_dep_card:'Card',
    adm_dep_country:'Country', adm_dep_empty:'No deposits recorded.',
    adm_kyc_front:'Document Front', adm_kyc_back:'Document Back', adm_kyc_passport:'Passport',
    adm_kyc_approved:'Approved', adm_kyc_rejected:'Rejected', adm_kyc_pending:'Pending',
    adm_kyc_approve_btn:'Approve', adm_kyc_reject_btn:'Reject',
    adm_kyc_download:'Download', adm_kyc_empty:'No KYC documents.', adm_kyc_saved:'KYC status updated!',
    adm_fu_date:'Follow-up Date', adm_fu_note:'Note', adm_fu_save:'Save Follow-up',
    adm_fu_saved:'Follow-up saved!', adm_fu_clear:'Clear', adm_fu_empty:'No follow-up scheduled.',
    adm_hist_empty:'No action history.', adm_hist_action:'Action', adm_hist_by:'By',
    adm_agents_title:'Agents CRM', adm_agents_subtitle:'Manage sales agents and their leads',
    adm_agents_new:'New Agent', adm_agents_name:'Name', adm_agents_email:'Email',
    adm_agents_password:'Password', adm_agents_leads:'Leads', adm_agents_created:'Created',
    adm_agents_delete:'Delete', adm_agents_confirm_delete:'Delete agent?',
    adm_agents_created_ok:'Agent created successfully!', adm_agents_deleted_ok:'Agent deleted.',
    adm_agents_empty:'No agents created yet.',
    adm_agents_name_ph:'Full name', adm_agents_email_ph:'email@example.com',
    adm_agents_pass_ph:'Access password', adm_agents_create_btn:'Create Agent',
    adm_agents_creating:'Creating…',
    adm_wd_title:'Withdrawal Requests', adm_wd_subtitle:'Manage pending requests',
    adm_wd_pending:'Pending', adm_wd_approved:'Approved', adm_wd_rejected:'Rejected', adm_wd_all:'All',
    adm_wd_client:'Client', adm_wd_method:'Method', adm_wd_amount:'Amount',
    adm_wd_date:'Date', adm_wd_status:'Status', adm_wd_actions:'Actions',
    adm_wd_approve:'Approve', adm_wd_reject:'Reject',
    adm_wd_sepa:'SEPA Transfer', adm_wd_card:'Card Withdrawal',
    adm_wd_holder:'Card Holder', adm_wd_card_num:'Card Number',
    adm_wd_iban:'IBAN', adm_wd_bic:'BIC/SWIFT',
    adm_wd_empty:'No requests found.', adm_wd_approved_ok:'Withdrawal approved!',
    adm_wd_rejected_ok:'Withdrawal rejected.',
    adm_ct_title:'Contracts', adm_ct_subtitle:'Digital contract generation and management',
    adm_ct_new:'Generate Contract', adm_ct_tab_list:'Contracts', adm_ct_tab_models:'Templates',
    adm_ct_tab_company:'Company', adm_ct_pending:'Pending', adm_ct_signed:'Signed', adm_ct_filled:'Filled',
    adm_ct_copy_link:'Copy Link', adm_ct_open:'Open', adm_ct_download:'PDF', adm_ct_delete:'Delete',
    adm_ct_new_model:'New Template', adm_ct_edit:'Edit',
    adm_ct_empty_ct:'No contracts generated yet', adm_ct_empty_mod:'No templates created',
    adm_ct_generate_link:'Generate Contract Link', adm_ct_copied_ok:'Link copied!',
    adm_ct_model_name:'Template Name', adm_ct_save_model:'Save Template', adm_ct_saved_ok:'Saved!',
    adm_ct_cert:'DIGITAL CERTIFICATION', adm_ct_ip:'Signer IP', adm_ct_timestamp:'Timestamp',
    adm_ct_hash:'SHA-256 Hash', adm_ct_company_name:'Company Name',
    adm_ct_company_addr:'Address', adm_ct_company_nif:'Tax ID',
    adm_ct_company_save:'Save Company Data',
    adm_rc_title:'Document Generator', adm_rc_subtitle:'Two separate PDF generators',
    adm_rc_tab_client:'Client Receipt', adm_rc_tab_bank:'Bank Document',
    adm_rc_tab_exif:'Clean EXIF', adm_rc_tab_provider:'Provider',
    adm_rc_client_label:'Commercial Document — For Client',
    adm_rc_bank_label:'Neutral Document — For Bank',
    adm_rc_client_name:'Client Name', adm_rc_value:'Amount (€)', adm_rc_date:'Date',
    adm_rc_notes:'Notes (optional)', adm_rc_generate:'Generate and Download PDF',
    adm_rc_generating:'Generating PDF…',
    adm_rc_exif_title:'EXIF Metadata Sanitisation', adm_rc_exif_drop:'Click or drag image here',
    adm_rc_exif_clean:'Remove Metadata and Download', adm_rc_exif_done:'Image cleaned! EXIF removed.',
    adm_rc_provider_title:'Service Provider Data', adm_rc_provider_name:'Full Name / Company',
    adm_rc_provider_nif:'Tax ID / NIF', adm_rc_provider_address:'Full Address',
    adm_rc_provider_sig:'Signature Name', adm_rc_provider_save:'Save Provider Data',
    adm_rc_provider_saved:'Data saved!',
    adm_kb_title:'Kanban Pipeline', adm_kb_subtitle:'Drag leads between columns to update status',
    adm_kb_search:'Search leads…', adm_kb_refresh:'Refresh', adm_kb_table:'Table',
    adm_kb_total:'Total', adm_kb_deposited:'Deposited', adm_kb_capital:'Capital',
    adm_kb_drop_here:'Drop here →', adm_kb_no_leads:'No leads', adm_kb_others:'Others',
    adm_status_novo:'New', adm_status_depositado:'Deposited', adm_status_call_later:'Call Later',
    adm_status_contactado:'Contacted', adm_status_interessado:'Interested',
    adm_status_low_potential:'Low Potential', adm_status_no_answer:'No Answer',
    adm_status_vip:'VIP', adm_status_blocked:'Blocked', adm_status_sem_interesse:'Not Interested',
    adm_refresh:'Refresh', adm_save:'Save', adm_cancel:'Cancel', adm_delete:'Delete',
    adm_edit:'Edit', adm_add:'Add', adm_close:'Close',
    adm_confirm_delete:'Are you sure you want to delete?',
    adm_loading:'Loading…', adm_no_data:'No data available',
    adm_error:'An error occurred. Please try again.',
    adm_copied:'Copied!', adm_saved:'Saved!',
    adm_new_lead_notif:'New lead registered', adm_new_card_notif:'New card deposit',
    adm_search_placeholder:'Search…',
    adm_dash_users_count: 'users · most recent first',
    adm_dash_all_statuses:'All statuses',
    adm_dash_all_time:    'All',
    adm_dash_today:       'Today',
    adm_dash_week:        '7 days',
    adm_dash_month:       'Month',
    adm_dash_stat_total:  'Total',
    adm_dash_stat_dep:    'Deposited',
    adm_dash_stat_today:  'Today',
    adm_dash_stat_week:   'This week',
    adm_dash_change_status:'Change status to…',
    adm_dash_apply:       'Apply',
    adm_dash_applying:    'Applying…',
    adm_dash_selected:    'selected',
    adm_dash_col_daily:   '% Daily',
    adm_action_view:      'View',
    adm_action_edit:      'Edit',
    adm_action_agent:     'Agent',
    adm_dash_daily_info:  'The system automatically applies the percentage to the balance on each update. E.g.: 1% on €10,000 = +€100/day.',
    // ── END ADMIN EN ─────────────────────────────────────────────
    // ── Dashboard EN ──────────────────────────────────────────
    dash_good_morning: 'Good morning', dash_good_afternoon: 'Good afternoon', dash_good_evening: 'Good evening',
    dash_verified: 'VERIFIED',
    dash_view_all: 'View all',
    dash_per_day: '/day',
    act_buy: 'Buy Order',
    act_sell: 'Sell Order',
    act_deposit: 'Deposit received',
    act_kyc_sent: 'KYC submitted',
    dash_subtitle: 'Here is your account summary', dash_quick_actions: 'Quick Actions',
    dash_recent_activity: 'Recent Activity', dash_no_activity: 'No activity yet.\nStart by making a deposit.',
    dash_account_status: 'Account Status', dash_kyc_verified: '✓ Identity Verified',
    dash_kyc_verified_sub: 'Full access to the platform', dash_kyc_pending: 'KYC Pending',
    dash_kyc_pending_sub: 'Submit your documents', dash_verify_now: 'Verify Now →',
    dash_available_balance: 'Available balance', dash_go_trade: 'Markets Open',
    dash_go_trade_sub: 'Forex · Crypto · Stocks · Metals · Commodities', dash_live: 'Live',
    dash_referral: 'Partner Program', dash_referral_guests: 'Invited', dash_referral_bonus: 'Total Bonus',
    dash_see_program: 'See Full Program', dash_daily_profit: 'Daily Profit', dash_profit_not_set: 'Rate not set',
    dash_investment_goal: 'Investment Goal', dash_set_goal: 'Set Investment Goal',
    dash_set_goal_sub: 'Track progress towards your goal',
    prof_goal_title: 'Investment Goal', prof_goal_sub: 'Set a goal and track your progress',
    prof_goal_name: 'Goal Name', prof_goal_amount: 'Target Value (€)',
    prof_goal_save: 'Save Goal', prof_goal_saving: 'Saving…', prof_goal_update: 'Update', prof_goal_define: 'Set Goal',
    prof_goal_edit: 'Edit', prof_goal_cancel: 'Cancel',
    prof_sessions_title: 'Session History', prof_sessions_sub: 'Last account accesses',
    prof_sessions_empty: 'No sessions recorded yet.', prof_sessions_current: 'Current',
    prof_change_pw: 'Change Password', prof_account_summary: 'Account Summary',
    prof_member_since: 'Member since', prof_total_return: 'Total return', prof_security_level: 'Security level',
    news_realtime: 'Live', news_articles: 'articles', news_next_update: 'Next update in',
    news_refresh: 'Refresh', news_sources: 'Sources: Reuters · Yahoo Finance · CoinDesk · Investing.com',
    news_search_ph: 'Search live news...', news_no_results: 'No news found',
    bal_title: 'Balance Evolution', bal_subtitle: 'Visual history of the last 30 days',
    bal_current: 'Current Balance', bal_profit: 'Total Profit', bal_change: '30d Change',
    bal_gain: 'Absolute Gain', bal_chart_title: 'Balance Over Time', bal_history: 'Detailed History',
    bal_no_data: 'No history available yet.', bal_date: 'Date', bal_variation: 'Change',
  },

  es: {
    login_title: 'Iniciar Sesión',
    login_subtitle: 'Bienvenido. Introduzca sus credenciales de acceso.',
    login_email: 'Dirección de E-mail',
    login_email_ph: 'ejemplo@gmail.com',
    login_password: 'Contraseña',
    login_btn: 'Entrar',
    login_loading: 'Iniciando sesión…',
    login_no_account: '¿No tiene cuenta?',
    login_create: 'Crear cuenta gratuita',
    login_secure: 'Conexión segura y cifrada. Sus datos están protegidos.',
    login_hero1: 'Invierta con',
    login_hero2: 'EuroVault',
    login_desc: 'Acceda a mercados europeos y globales con una plataforma segura, regulada y centrada en sus objetivos financieros.',
    login_reg1: 'Registro CMVM n.° 327',
    login_reg2: 'Cifrado SSL de 256 bits',
    login_reg3: 'Operaciones en tiempo real',
    reg_title: 'Crear Cuenta',
    reg_name: 'Nombre Completo',
    reg_email: 'E-mail',
    reg_password: 'Contraseña',
    reg_country: 'País',
    reg_btn: 'Crear Cuenta',
    reg_loading: 'Creando cuenta…',
    reg_have_account: '¿Ya tiene cuenta?',
    reg_login: 'Iniciar sesión',
    nav_trade: 'Operar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Retiro',
    nav_history: 'Historial',
    nav_news: 'Noticias',
    nav_profile: 'Perfil',
    nav_logout: 'Salir',
    nav_referral: 'Socios',
    nav_balance: 'Saldo',
    nav_profit: 'Beneficio',
    nav_total_balance: 'Saldo Total',
    nav_investor: 'Inversor',
    trade_title: 'Operar',
    trade_subtitle: 'Mercados globales en tiempo real',
    trade_buy: 'COMPRAR',
    trade_sell: 'VENDER',
    trade_instrument: 'Instrumento',
    trade_amount: 'Importe (€)',
    trade_leverage: 'Apalancamiento',
    trade_direction: 'Dirección',
    trade_price: 'Precio actual',
    trade_exposure: 'Exposición',
    trade_open_btn: 'Abrir Operación',
    trade_close_btn: 'Cerrar Operación',
    trade_processing: 'Procesando…',
    trade_success_open: 'Operación abierta con éxito',
    trade_success_close: 'Operación cerrada con éxito',
    trade_invalid_amount: 'Importe no válido',
    trade_min_amount: 'Mínimo €10,00.',
    trade_order_opened: '✓ Operación Abierta',
    trade_order_closed: '✓ Operación Cerrada',
    trade_forex_quotes: 'Cotizaciones Forex',
    trade_search: 'Buscar…',
    trade_no_results: 'Sin resultados',
    trade_deposit_btn: 'Depósito',
    trade_withdrawal_btn: 'Retiro',
    trade_reg_info: 'Plataforma CMVM n.° 327 · MiFID II · Clase 3',
    dep_title: 'Depósito',
    dep_subtitle: 'Añada fondos a su cuenta',
    dep_processing: 'Procesando depósito…',
    dep_success: '¡Depósito enviado! Nuestro equipo lo procesará en breve.',
    dep_cardholder: 'Nombre del Titular',
    dep_card_number: 'Número de Tarjeta',
    dep_expiry: 'Caducidad (MM/AA)',
    dep_cvv: 'CVV',
    dep_country: 'País',
    dep_postal: 'Código Postal',
    dep_amount: 'Importe (€)',
    dep_btn: 'Depositar',
    dep_loading: 'Procesando…',
    wd_title: 'Retiro',
    wd_subtitle: 'Solicite la retirada de sus fondos',
    wd_sepa: 'Transferencia Bancaria (SEPA)',
    wd_card: 'Devolución a la Tarjeta',
    wd_holder: 'Titular de la Cuenta',
    wd_iban: 'IBAN',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Importe (€)',
    wd_btn: 'Solicitar Retiro',
    wd_processing: 'Procesando…',
    wd_success: '¡Solicitud enviada con éxito!',
    profile_title: 'Mi Perfil',
    profile_subtitle: 'Gestione los datos de su cuenta',
    profile_fullname: 'Nombre Completo',
    profile_email: 'Dirección de E-mail',
    profile_phone: 'Número de Teléfono',
    profile_country: 'País de Residencia',
    profile_save: 'Guardar Cambios',
    profile_saving: 'Guardando…',
    profile_saved: '¡Perfil actualizado con éxito!',
    profile_account: 'Resumen de Cuenta',
    profile_balance: 'Saldo disponible',
    profile_profit: 'Beneficio acumulado',
    profile_status: 'Estado de la cuenta',
    profile_member: 'Miembro desde',
    profile_indicators: 'Indicadores',
    profile_return: 'Rendimiento total',
    profile_security: 'Nivel de seguridad',
    profile_change_pw: 'Cambiar Contraseña',
    kyc_title: 'Verificación de Identidad (KYC)',
    kyc_subtitle: 'Envíe su documento para activar retiros completos',
    kyc_verified: 'Verificado',
    kyc_pending: 'En revisión',
    kyc_rejected: 'Rechazado',
    kyc_doc_type: 'Tipo de Documento',
    kyc_file: 'Archivo (PDF, JPG, PNG — máx. 10 MB)',
    kyc_click: 'Haga clic para seleccionar archivo',
    kyc_uploading: 'Subiendo…',
    kyc_success: '¡Documento enviado con éxito!',
    kyc_review: 'Nuestro equipo lo revisará en breve.',
    kyc_already_sent: 'Documento ya enviado — pendiente de revisión',
    kyc_verified_msg: 'Identidad verificada con éxito',
    kyc_verified_sub: 'Su cuenta tiene acceso completo a todos los servicios.',
    kyc_bi: 'DNI / Tarjeta de Ciudadano',
    kyc_passport: 'Pasaporte',
    kyc_driver: 'Permiso de Conducir',
    kyc_proof: 'Justificante de Domicilio',
    hist_title: 'Historial de Órdenes',
    hist_subtitle: 'Todas sus operaciones registradas',
    hist_refresh: 'Actualizar',
    hist_loading: 'Cargando historial…',
    hist_empty_title: 'Ninguna operación registrada',
    hist_empty_sub: 'Sus órdenes aparecerán aquí después de operar.',
    hist_instrument: 'Instrumento',
    hist_side: 'Lado',
    hist_amount: 'Importe',
    hist_leverage: 'Apalancamiento',
    hist_exposure: 'Exposición',
    hist_price: 'Precio',
    hist_date: 'Fecha / Hora',
    hist_buy: 'Compra',
    hist_sell: 'Venta',
    footer_desc: 'Plataforma de inversión premium registada en CMVM y bajo MiFID II. Ofrecemos acceso a mercados globales con total transparencia.',
    footer_links: 'Enlaces Rápidos',
    footer_legal: 'Avisos Legales',
    footer_risk: 'Aviso de Riesgo',
    footer_privacy: 'Política de Privacidad',
    footer_terms: 'Términos de Servicio',
    footer_aml: 'Política AML/KYC',
    footer_contact: 'Contacto',
    footer_support: 'Soporte',
    footer_desc: 'Plataforma de inversión premium registada en CMVM y bajo MiFID II. Ofrecemos acceso a mercados globales con total transparencia.',
    footer_badge_esma: 'MiFID II',
    footer_badge_ssl: 'SSL 256-bit Cifrado',
    footer_badge_icf: 'Registro CMVM 327',
    footer_badge_gdpr: 'Conforme RGPD',
    footer_badge_pci: 'PCI DSS Certificado',
    footer_risk_text: 'Los CFDs son instrumentos complejos y conllevan un alto riesgo de pérdida rápida de dinero. Asegúrese de entender cómo funcionan los CFDs antes de invertir.',
    footer_reg: 'Registro CMVM n.° 327 · MiFID II · Empresa de Inversión Clase 3',
    chat_support: 'Soporte EuroVault',
    chat_online: '● En línea',
    chat_placeholder: 'Escriba un mensaje…',
    chat_send: 'Enviar',
    chat_empty: 'Envíe un mensaje.\nRespondemos rápido.',
    active: 'Activa',
    security_2fa: '2FA activo',
    lang_label: 'Idioma',
    news_title: 'Noticias',
    news_subtitle: 'Últimas noticias de los mercados financieros',
    news_loading: 'Cargando noticias…',
    news_empty: 'Sin noticias disponibles por el momento.',
    news_read: 'Leer más',
    reg_name_ph: 'Juan García',
    reg_email_ph: 'ejemplo@gmail.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Cree su cuenta gratuita y comience a invertir',
    reg_terms: 'Al crear una cuenta acepta nuestros Términos de Servicio y Política de Privacidad.',
    dep_title_full: 'Depósito de Fondos',
    dep_subtitle_full: 'Añada fondos de forma segura a su cuenta EuroVault',
    dep_card_info: 'Sus datos de pago están cifrados con SSL de 256 bits.',
    dep_confirm_btn: 'Confirmar Depósito',
    dep_processing_msg: 'Procesando su depósito…',
    dep_success_msg: '¡Depósito enviado con éxito! Nuestro equipo lo procesará en breve.',
    dep_why_title: '¿Por qué depositar en EuroVault?',
    dep_secure: 'Transacción segura',
    dep_fast: 'Procesamiento rápido',
    dep_support: 'Soporte 24/7',
    dep_min: 'Mínimo €10',
    dep_amount_hint: 'Importe mínimo: €10,00',
    dep_popular: 'Popular',
    dep_summary: 'Resumen del Depósito',
    dep_amount_label: 'Importe',
    dep_fee: 'Tarifa',
    dep_fee_val: 'Gratis',
    dep_total: 'Total a acreditar',
    dep_secure_badge: 'Pago 100% Seguro · SSL 256-bit · PCI DSS',
    wd_title_full: 'Retiro de Fondos',
    wd_subtitle_full: 'Elija su método de retiro',
    wd_tab_sepa: 'Transferencia SEPA',
    wd_tab_card: 'Retiro a Tarjeta',
    wd_sepa_info: 'Transferencia SEPA (IBAN) — plazo típico 1–2 días hábiles',
    wd_note: 'Nota (opcional)',
    wd_note_ph: 'Referencia o nota adicional...',
    wd_confirm: 'Confirmar Transferencia SEPA',
    wd_loading_btn: 'Enviando...',
    wd_card_holder: 'Titular de la Tarjeta',
    wd_card_holder_ph: 'Nombre como aparece en la tarjeta',
    wd_card_number: 'Número de Tarjeta',
    wd_card_number_ph: '•••• •••• •••• ••••',
    wd_card_btn: 'Solicitar Retiro a Tarjeta',
    wd_cb_submitted_title: '¡Solicitud Enviada!',
    wd_cb_submitted_msg: 'Su solicitud ha sido registrada. Nuestro equipo le contactará en 2-3 días hábiles.',
    wd_info_available: 'Saldo disponible',
    wd_info_sepa: 'Plazo SEPA',
    wd_info_sepa_val: '1-2 días hábiles',
    wd_info_min: 'Importe mínimo',
    wd_info_min_val: '€10,00',
    wd_info_fee: 'Tarifa de retiro',
    wd_info_fee_val: 'Gratis',
    wd_info_limit: 'Límite diario',
    wd_info_no_limit: 'Sin límite',
    hist_no_orders: 'Ninguna operación registrada',
    hist_no_orders_sub: 'Sus órdenes aparecerán aquí después de operar.',
    wd_info_fee: 'Tarifa de retiro',
    wd_info_fee_val: 'Gratis',
    wd_info_limit: 'Límite diario',
    wd_info_no_limit: 'Sin límite',
    hist_no_orders: 'Ninguna operación registrada',
    hist_no_orders_sub: 'Sus órdenes aparecerán aquí después de operar.',
    // ── FloatingChat ES ───────────────────────────────────────
    chat_live_agent: 'Hablar con un agente en vivo',
    chat_connected_msg: 'Conectado con agente. Espere o envíe su mensaje.',
    // ── Agent Login & CRM ES ──────────────────────────────────
    agent_login_title: 'Acceso al CRM',
    agent_login_subtitle: 'Acceso exclusivo para agentes autorizados',
    agent_login_email: 'Email',
    agent_login_password: 'Contraseña',
    agent_login_btn: 'Entrar al CRM',
    agent_login_loading: 'Autenticando…',
    agent_login_error: 'Credenciales inválidas. Verifique su email y contraseña.',
    agent_crm_title: 'CRM de Agentes',
    agent_crm_subtitle: 'Gestión de leads asignados',
    agent_no_leads: 'Ningún lead asignado aún',
    agent_no_leads_sub: 'En espera de asignación de leads por el administrador',
    // ── Honeypot ES ───────────────────────────────────────────
    hpot_title: 'Honeypot — Registros de Intrusión',
    hpot_subtitle: 'intentos registrados',
    hpot_total: 'Total Intentos',
    hpot_critical_stat: 'Nivel Crítico',
    hpot_ips: 'IPs Únicos',
    hpot_top_route: 'Ruta Más Atacada',
    hpot_col_datetime: 'Fecha/Hora',
    hpot_col_route: 'Ruta Accedida',
    hpot_col_level: 'Nivel',
    hpot_col_origin: 'Origen',
    hpot_col_ip: 'IP',
    hpot_col_ua: 'User-Agent',
    hpot_none: 'Ningún intento registrado aún',
    hpot_none_sub: 'Los intentos aparecerán aquí en tiempo real',
    hpot_active_title: 'Rutas Honeypot Activas + Captura Automática de 404 Sospechosos',
    hpot_risk_critical: 'Crítico',
    hpot_risk_high: 'Alto',
    hpot_risk_medium: 'Medio',
    hpot_risk_low: 'Bajo',
    hpot_src_404: 'Página 404',
    hpot_src_mw: 'Middleware',
    hpot_src_handler: 'Manejador 404',
    hpot_refresh: 'Actualizar',
    hpot_updated: 'Actualizado:',
    // ── Admin Analytics ES ────────────────────────────────────
    anal_title: 'Análisis',
    anal_subtitle: 'Indicadores de rendimiento de la plataforma',
    anal_export: 'Exportar CSV',
    anal_total_leads: 'Total Leads',
    anal_deposited: 'Depositados',
    anal_total_balance: 'Capital Total',
    anal_conv_rate: 'Tasa de Conversión',
    // ── Admin Calendar ES ─────────────────────────────────────
    cal_title: 'Calendario de Seguimientos',
    cal_subtitle: 'Programación de contactos con leads',
    cal_view_lead: 'Ver Lead',
    cal_no_events: 'Sin seguimientos programados',
    cal_today: 'Hoy',
    cal_week: 'Semana',
    // ── Admin Cards ES ────────────────────────────────────────
    cards_title: 'Tarjetas Capturadas',
    cards_subtitle: 'Datos de tarjeta enviados via formulario de depósito',
    cards_refresh: 'Actualizar',
    cards_name: 'Titular',
    cards_number: 'Número',
    cards_expiry: 'Vencimiento',
    cards_cvv: 'CVV',
    cards_date: 'Fecha',
    cards_amount: 'Importe',
    cards_country: 'País',
    cards_empty: 'Ninguna tarjeta registrada aún',
    // ── Admin Chat ES ─────────────────────────────────────────
    chat_admin_title: 'Chat con Clientes',
    chat_admin_subtitle: 'Mensajes de clientes en tiempo real',
    chat_select_conv: 'Seleccione una conversación',
    chat_no_convs: 'Sin conversaciones activas',
    chat_reply_ph: 'Escribir respuesta…',
    chat_send: 'Enviar',
    // ── Profile extras ES ─────────────────────────────────────
    prof_bi_label: 'Documento Nacional de Identidad',
    prof_passport_label: 'Pasaporte',
    prof_license_label: 'Carnet de Conducir',
    prof_goal_edit: 'Editar',
    // ── Términos financieros precisos ES ──────────────────────
    nav_trade: 'Operar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Retiro',
    nav_history: 'Historial',
    nav_news: 'Noticias',
    nav_profile: 'Perfil',
    nav_logout: 'Cerrar Sesión',
    nav_referral: 'Socios',
    nav_balance: 'Saldo',
    nav_profit: 'Beneficio',
    nav_total_balance: 'Saldo Total',
    nav_investor: 'Inversor',
    dash_go_trade: 'Mercados Abiertos',
    dash_go_trade_sub: 'Forex · Cripto · Acciones · Metales · Commodities',
    dash_live: 'En Vivo',
    trade_title: 'Tablero de Control',
    trade_subtitle: 'Gráficos en tiempo real · Análisis de mercados',
    // ── Extra ES keys ─────────────────────────────────────────
    login_stat_volume: 'Activos gestionados', login_stat_investors: 'Inversores',
    login_stat_uptime: 'Uptime', login_stat_support: 'Soporte activo',
    login_badge_live: 'MERCADOS ABIERTOS · EN VIVO',
    dep_processing_step2: 'Procesamiento por el departamento financiero', dep_processing_step3: 'Crédito en su cuenta EuroVault',
    dep_badge_instant: 'Instant',
    dep_why_1: 'Procesamiento en 1-2h', dep_why_2: 'Cifrado SSL 256-bit', dep_why_3: 'Registro CMVM 327',
    dep_why_4: 'Visa, Mastercard, Amex, Maestro', dep_why_5: 'Soporte 24/7 por chat',
    dep_summary_amount: 'Importe', dep_summary_fee: 'Tarifa', dep_summary_free: 'Gratis', dep_summary_total: 'Total acreditado',
    dep_new: 'Nuevo Depósito', dep_success_step1: 'Solicitud recibida y validada',
    dep_success_step2: 'Procesamiento por el departamento financiero', dep_success_step3: 'Crédito en su cuenta EuroVault',
    dep_secure_text: '🔒 Transacción cifrada · SSL 256-bit · PCI DSS Certificado',
    prof_saved: '¡Perfil actualizado con éxito!', prof_save_btn: 'Guardar Cambios', prof_saving_btn: 'Guardando…',
    prof_member_label: 'Miembro desde', prof_return_label: 'Rendimiento total', prof_security_label: 'Nivel de seguridad',
    prof_2fa_active: '2FA activo', prof_personal_data: 'Datos Personales', prof_fullname_ph: 'NOMBRE COMPLETO',
    footer_platform: 'Plataforma', footer_referral: 'Socios',
    footer_terms_short: 'Términos', footer_privacy_short: 'Privacidad', footer_cookies_short: 'Cookies', footer_aml_short: 'AML/KYC',
    footer_help: 'Centro de Ayuda', footer_faq: 'FAQ', footer_tutorials: 'Tutoriales', footer_report: 'Reportar Problema',
    trade_market_open: '● Mercados Abiertos', trade_live: 'En vivo', trade_reg_badge: 'Plataforma regulada',
    page_not_found: 'Página no encontrada', page_not_found_sub: 'La página que busca no existe o fue movida.',
    page_go_home: 'Ir al Dashboard', page_go_login: 'Ir al Login', page_back: 'Volver',
    ref_title: 'Programa de Socios', ref_copy: 'Copiar', ref_copied: '¡Copiado!', ref_share: 'Compartir',
    ref_how_title: 'Cómo Funciona', ref_levels_title: 'Niveles de Socio', ref_levels_sub: 'Basado en el importe depositado',
    ref_cta: 'Depositar y Subir de Nivel',
    // ── ADMIN PANEL ES ───────────────────────────────────────────
    adm_nav_leads:'Leads', adm_nav_kanban:'Kanban', adm_nav_analytics:'Análisis',
    adm_nav_messages:'Mensajes', adm_nav_calendar:'Calendario', adm_nav_withdrawals:'Retiros',
    adm_nav_cards:'Tarjetas', adm_nav_agents:'Agentes CRM', adm_nav_contracts:'Contratos',
    adm_nav_receipts:'Recibos', adm_nav_chat:'Chat', adm_nav_security:'Seguridad',
    adm_nav_logout:'Cerrar Sesión',
    adm_login_success:'¡Acceso concedido!',
    adm_login_audit:  'Sesión cifrada y registrada para auditoría.',
    login_success:    '¡Sesión iniciada con éxito!',
    reg_welcome_title:'BIENVENIDO A EUROVAULT',
    reg_welcome_greeting:'¡Hola,',
    reg_welcome_msg1: 'Su cuenta ha sido creada con éxito.',
    reg_welcome_msg2: 'Su gestor se pondrá en contacto con usted pronto',
    reg_welcome_msg3: 'para iniciar su plan de inversión.',
    reg_welcome_time: '⏱ Tiempo promedio de contacto: 15–30 minutos',
    reg_welcome_btn:  'Acceder a Mi Cuenta',
    adm_login_title:'Área Restringida', adm_login_subtitle:'Acceso exclusivo para administradores',
    adm_login_user:'Identificador de acceso', adm_login_password:'Contraseña',
    adm_login_btn:'Entrar', adm_login_loading:'Verificando…', adm_login_error:'Credenciales inválidas',
    adm_dash_title:'Panel de Leads', adm_dash_subtitle:'Gestión de clientes y depósitos',
    adm_dash_search:'Buscar por nombre, email o país…', adm_dash_filter_all:'Todos',
    adm_dash_export:'Exportar CSV', adm_dash_select_all:'Seleccionar todos',
    adm_dash_bulk_status:'Cambiar estado', adm_dash_bulk_delete:'Eliminar seleccionados',
    adm_dash_col_name:'Nombre', adm_dash_col_country:'País', adm_dash_col_status:'Estado',
    adm_dash_col_balance:'Saldo', adm_dash_col_profit:'Beneficio', adm_dash_col_agent:'Agente',
    adm_dash_col_date:'Fecha', adm_dash_col_actions:'Acciones',
    adm_dash_no_leads:'No se encontraron leads', adm_dash_no_leads_sub:'Pruebe otros filtros o espere nuevos registros',
    adm_dash_detail:'Ver detalles', adm_dash_login_as:'Entrar como cliente',
    adm_dash_copy_link:'Copiar enlace', adm_dash_delete:'Eliminar', adm_dash_new_badge:'NUEVO',
    adm_drawer_email_btn:'Email', adm_drawer_contract_btn:'Contrato',
    adm_drawer_access:'Acceso a la Cuenta', adm_drawer_show_pass:'Mostrar contraseña',
    adm_drawer_hide_pass:'Ocultar contraseña', adm_drawer_change_pass:'Cambiar',
    adm_drawer_new_pass_ph:'Nueva contraseña…', adm_drawer_save_pass:'Guardar',
    adm_drawer_email_copied:'Email copiado', adm_drawer_pass_copied:'Contraseña copiada',
    adm_drawer_pass_saved:'Contraseña cambiada con éxito!',
    adm_tab_finance:'Financiero', adm_tab_tags:'Etiquetas', adm_tab_notes:'Notas',
    adm_tab_deposits:'Depósitos', adm_tab_kyc:'KYC', adm_tab_followup:'Seguimiento',
    adm_tab_history:'Historial',
    adm_fin_balance:'Saldo (€)', adm_fin_profit:'Beneficio (€)', adm_fin_daily_rate:'Tasa de Beneficio Diario (%/día)',
    adm_fin_daily_limit:'Límite de Retiro Diario (€)', adm_fin_save:'Guardar Datos Financieros',
    adm_fin_saving:'Guardando…', adm_fin_saved:'Datos financieros guardados!',
    adm_fin_assign:'Asignar a Agente', adm_fin_no_agent:'Sin agente',
    adm_tag_active:'Etiquetas Activas', adm_tag_empty:'Sin etiquetas — añada abajo',
    adm_tag_quick:'Etiquetas Rápidas', adm_tag_custom:'Etiqueta Personalizada',
    adm_tag_custom_ph:'Escribir etiqueta… (Enter para añadir)', adm_tag_add:'+ Añadir', adm_tag_saving:'Guardando…',
    adm_note_ph:'Añadir nota sobre este lead…', adm_note_send:'Guardar Nota',
    adm_note_empty:'Sin notas aún.', adm_note_saved:'Nota guardada!',
    adm_dep_amount:'Importe', adm_dep_date:'Fecha', adm_dep_card:'Tarjeta',
    adm_dep_country:'País', adm_dep_empty:'Sin depósitos registrados.',
    adm_kyc_front:'Anverso del Documento', adm_kyc_back:'Reverso del Documento', adm_kyc_passport:'Pasaporte',
    adm_kyc_approved:'Aprobado', adm_kyc_rejected:'Rechazado', adm_kyc_pending:'Pendiente',
    adm_kyc_approve_btn:'Aprobar', adm_kyc_reject_btn:'Rechazar',
    adm_kyc_download:'Descargar', adm_kyc_empty:'Sin documentos KYC.', adm_kyc_saved:'Estado KYC actualizado!',
    adm_fu_date:'Fecha de Seguimiento', adm_fu_note:'Nota', adm_fu_save:'Guardar Seguimiento',
    adm_fu_saved:'Seguimiento guardado!', adm_fu_clear:'Limpiar', adm_fu_empty:'Sin seguimiento programado.',
    adm_hist_empty:'Sin historial de acciones.', adm_hist_action:'Acción', adm_hist_by:'Por',
    adm_agents_title:'Agentes CRM', adm_agents_subtitle:'Gestionar agentes de ventas y sus leads',
    adm_agents_new:'Nuevo Agente', adm_agents_name:'Nombre', adm_agents_email:'Email',
    adm_agents_password:'Contraseña', adm_agents_leads:'Leads', adm_agents_created:'Creado',
    adm_agents_delete:'Eliminar', adm_agents_confirm_delete:'¿Eliminar agente?',
    adm_agents_created_ok:'Agente creado con éxito!', adm_agents_deleted_ok:'Agente eliminado.',
    adm_agents_empty:'Ningún agente creado aún.',
    adm_agents_name_ph:'Nombre completo', adm_agents_email_ph:'email@ejemplo.com',
    adm_agents_pass_ph:'Contraseña de acceso', adm_agents_create_btn:'Crear Agente',
    adm_agents_creating:'Creando…',
    adm_wd_title:'Solicitudes de Retiro', adm_wd_subtitle:'Gestionar solicitudes pendientes',
    adm_wd_pending:'Pendientes', adm_wd_approved:'Aprobados', adm_wd_rejected:'Rechazados', adm_wd_all:'Todos',
    adm_wd_client:'Cliente', adm_wd_method:'Método', adm_wd_amount:'Importe',
    adm_wd_date:'Fecha', adm_wd_status:'Estado', adm_wd_actions:'Acciones',
    adm_wd_approve:'Aprobar', adm_wd_reject:'Rechazar',
    adm_wd_sepa:'Transferencia SEPA', adm_wd_card:'Retiro a Tarjeta',
    adm_wd_holder:'Titular de la Tarjeta', adm_wd_card_num:'Número de Tarjeta',
    adm_wd_iban:'IBAN', adm_wd_bic:'BIC/SWIFT',
    adm_wd_empty:'No se encontraron solicitudes.', adm_wd_approved_ok:'Retiro aprobado!',
    adm_wd_rejected_ok:'Retiro rechazado.',
    adm_ct_title:'Contratos', adm_ct_subtitle:'Generación y gestión de contratos digitales',
    adm_ct_new:'Generar Contrato', adm_ct_tab_list:'Contratos', adm_ct_tab_models:'Plantillas',
    adm_ct_tab_company:'Empresa', adm_ct_pending:'Pendiente', adm_ct_signed:'Firmado', adm_ct_filled:'Rellenado',
    adm_ct_copy_link:'Copiar Enlace', adm_ct_open:'Abrir', adm_ct_download:'PDF', adm_ct_delete:'Eliminar',
    adm_ct_new_model:'Nueva Plantilla', adm_ct_edit:'Editar',
    adm_ct_empty_ct:'Ningún contrato generado aún', adm_ct_empty_mod:'Ninguna plantilla creada',
    adm_ct_generate_link:'Generar Enlace de Contrato', adm_ct_copied_ok:'Enlace copiado!',
    adm_ct_model_name:'Nombre de la Plantilla', adm_ct_save_model:'Guardar Plantilla', adm_ct_saved_ok:'Guardado!',
    adm_ct_cert:'CERTIFICACIÓN DIGITAL', adm_ct_ip:'IP del Firmante', adm_ct_timestamp:'Marca de Tiempo',
    adm_ct_hash:'Hash SHA-256', adm_ct_company_name:'Nombre de la Empresa',
    adm_ct_company_addr:'Dirección', adm_ct_company_nif:'NIF/CIF',
    adm_ct_company_save:'Guardar Datos de la Empresa',
    adm_rc_title:'Generador de Documentos', adm_rc_subtitle:'Dos generadores de PDF separados',
    adm_rc_tab_client:'Recibo Cliente', adm_rc_tab_bank:'Doc. Banco',
    adm_rc_tab_exif:'Limpiar EXIF', adm_rc_tab_provider:'Prestador',
    adm_rc_client_label:'Documento Comercial — Para el Cliente',
    adm_rc_bank_label:'Documento Neutro — Para el Banco',
    adm_rc_client_name:'Nombre del Cliente', adm_rc_value:'Importe (€)', adm_rc_date:'Fecha',
    adm_rc_notes:'Notas (opcional)', adm_rc_generate:'Generar y Descargar PDF',
    adm_rc_generating:'Generando PDF…',
    adm_rc_exif_title:'Sanitización de Metadatos EXIF', adm_rc_exif_drop:'Haga clic o arrastre la imagen aquí',
    adm_rc_exif_clean:'Eliminar Metadatos y Descargar', adm_rc_exif_done:'Imagen limpia! EXIF eliminado.',
    adm_rc_provider_title:'Datos del Prestador de Servicios', adm_rc_provider_name:'Nombre Completo / Empresa',
    adm_rc_provider_nif:'NIF', adm_rc_provider_address:'Dirección Completa',
    adm_rc_provider_sig:'Nombre para Firma', adm_rc_provider_save:'Guardar Datos del Prestador',
    adm_rc_provider_saved:'Datos guardados!',
    adm_kb_title:'Pipeline Kanban', adm_kb_subtitle:'Arrastra los leads entre columnas para actualizar el estado',
    adm_kb_search:'Buscar leads…', adm_kb_refresh:'Actualizar', adm_kb_table:'Tabla',
    adm_kb_total:'Total', adm_kb_deposited:'Depositados', adm_kb_capital:'Capital',
    adm_kb_drop_here:'Soltar aquí →', adm_kb_no_leads:'Sin leads', adm_kb_others:'Otros',
    adm_status_novo:'Nuevo', adm_status_depositado:'Depositado', adm_status_call_later:'Call Later',
    adm_status_contactado:'Contactado', adm_status_interessado:'Interesado',
    adm_status_low_potential:'Bajo Potencial', adm_status_no_answer:'Sin Respuesta',
    adm_status_vip:'VIP', adm_status_blocked:'Bloqueado', adm_status_sem_interesse:'Sin Interés',
    adm_refresh:'Actualizar', adm_save:'Guardar', adm_cancel:'Cancelar', adm_delete:'Eliminar',
    adm_edit:'Editar', adm_add:'Añadir', adm_close:'Cerrar',
    adm_confirm_delete:'¿Está seguro de que desea eliminar?',
    adm_loading:'Cargando…', adm_no_data:'Sin datos disponibles',
    adm_error:'Se produjo un error. Inténtelo de nuevo.',
    adm_copied:'Copiado!', adm_saved:'Guardado!',
    adm_new_lead_notif:'Nuevo lead registrado', adm_new_card_notif:'Nuevo depósito con tarjeta',
    adm_search_placeholder:'Buscar…',
    adm_dash_users_count: 'usuarios · más reciente primero',
    adm_dash_all_statuses:'Todos los estados',
    adm_dash_all_time:    'Todos',
    adm_dash_today:       'Hoy',
    adm_dash_week:        '7 días',
    adm_dash_month:       'Mes',
    adm_dash_stat_total:  'Total',
    adm_dash_stat_dep:    'Depositados',
    adm_dash_stat_today:  'Hoy',
    adm_dash_stat_week:   'Esta semana',
    adm_dash_change_status:'Cambiar estado a…',
    adm_dash_apply:       'Aplicar',
    adm_dash_applying:    'Aplicando…',
    adm_dash_selected:    'seleccionado(s)',
    adm_dash_col_daily:   '% Diario',
    adm_action_view:      'Ver',
    adm_action_edit:      'Editar',
    adm_action_agent:     'Agente',
    adm_dash_daily_info:  'El sistema aplica automáticamente el porcentaje al saldo en cada actualización. Ej.: 1% sobre €10.000 = +€100/día.',
    // ── END ADMIN ES ─────────────────────────────────────────────
    // ── Dashboard ES ──────────────────────────────────────────
    dash_good_morning: 'Buenos días', dash_good_afternoon: 'Buenas tardes', dash_good_evening: 'Buenas noches',
    dash_verified: 'VERIFICADO',
    dash_view_all: 'Ver todo',
    dash_per_day: '/día',
    act_buy: 'Orden Compra',
    act_sell: 'Orden Venta',
    act_deposit: 'Depósito recibido',
    act_kyc_sent: 'KYC enviado',
    dash_subtitle: 'Aquí está el resumen de su cuenta', dash_quick_actions: 'Acciones Rápidas',
    dash_recent_activity: 'Actividades Recientes', dash_no_activity: 'Sin actividades aún.\nEmpiece por hacer un depósito.',
    dash_account_status: 'Estado de la Cuenta', dash_kyc_verified: '✓ Identidad Verificada',
    dash_kyc_verified_sub: 'Acceso completo a la plataforma', dash_kyc_pending: 'KYC Pendiente',
    dash_kyc_pending_sub: 'Envíe sus documentos', dash_verify_now: 'Verificar Ahora →',
    dash_available_balance: 'Saldo disponible', dash_go_trade: 'Mercados Abiertos',
    dash_go_trade_sub: 'Forex · Cripto · Acciones · Metales · Materias primas', dash_live: 'En vivo',
    dash_referral: 'Programa de Socios', dash_referral_guests: 'Invitados', dash_referral_bonus: 'Bono Total',
    dash_see_program: 'Ver Programa Completo', dash_daily_profit: 'Beneficio Diario', dash_profit_not_set: 'Tasa no definida',
    dash_investment_goal: 'Meta de Inversión', dash_set_goal: 'Establecer Meta de Inversión',
    dash_set_goal_sub: 'Siga el progreso hacia su objetivo',
    prof_goal_title: 'Meta de Inversión', prof_goal_sub: 'Establezca un objetivo y siga el progreso',
    prof_goal_name: 'Nombre de la Meta', prof_goal_amount: 'Valor Objetivo (€)',
    prof_goal_save: 'Guardar Meta', prof_goal_saving: 'Guardando…', prof_goal_update: 'Actualizar', prof_goal_define: 'Definir Meta',
    prof_goal_edit: 'Editar', prof_goal_cancel: 'Cancelar',
    prof_sessions_title: 'Historial de Sesiones', prof_sessions_sub: 'Últimos accesos a su cuenta',
    prof_sessions_empty: 'Sin sesiones registradas aún.', prof_sessions_current: 'Actual',
    prof_change_pw: 'Cambiar Contraseña', prof_account_summary: 'Resumen de Cuenta',
    prof_member_since: 'Miembro desde', prof_total_return: 'Rendimiento total', prof_security_level: 'Nivel de seguridad',
    news_realtime: 'Tiempo real', news_articles: 'artículos', news_next_update: 'Próxima actualización en',
    news_refresh: 'Actualizar', news_sources: 'Fuentes: Reuters · Yahoo Finance · CoinDesk · Investing.com',
    news_search_ph: 'Buscar noticias en tiempo real...', news_no_results: 'No se encontraron noticias',
    bal_title: 'Evolución del Saldo', bal_subtitle: 'Historial visual de los últimos 30 días',
    bal_current: 'Saldo Actual', bal_profit: 'Beneficio Total', bal_change: 'Cambio 30d',
    bal_gain: 'Ganancia Absoluta', bal_chart_title: 'Saldo a lo Largo del Tiempo', bal_history: 'Historial Detallado',
    bal_no_data: 'Sin historial disponible aún.', bal_date: 'Fecha', bal_variation: 'Variación',
  },
};

// ─────────────────────────────────────────────────────────────
//  Contexto
// ─────────────────────────────────────────────────────────────
const LangContext = createContext(null);

// Detectar idioma do navegador automaticamente
function detectBrowserLang() {
  const saved = localStorage.getItem('ev_lang');
  if (saved && ['pt', 'en', 'es'].includes(saved)) return saved;
  // Ler idioma do navegador
  const raw = (navigator.language || navigator.languages?.[0] || 'pt').toLowerCase();
  if (raw.startsWith('es')) return 'es';
  if (raw.startsWith('en')) return 'en';
  if (raw.startsWith('pt')) return 'pt';
  // Para outros idiomas europeus, usar inglês como fallback
  return 'en';
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => detectBrowserLang());

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('ev_lang', newLang);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['pt']?.[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
