import React, { createContext, useContext, useState } from 'react';

// ─────────────────────────────────────────────────────────────
//  Dicionário de traduções
// ─────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  pt: {
    // ── Auth ──────────────────────────────────────────────────
    login_title: 'Iniciar Sessão',
    login_subtitle: 'Bem-vindo. Introduza as suas credenciais de acesso.',
    login_email: 'Endereço de E-mail',
    login_password: 'Palavra-Passe',
    login_btn: 'Entrar',
    login_loading: 'A entrar…',
    login_no_account: 'Não tem conta?',
    login_create: 'Criar conta gratuita',
    login_secure: 'Ligação segura e encriptada. Os seus dados estão protegidos.',
    login_hero1: 'Invista com',
    login_hero2: 'EuroVault',
    login_desc: 'Aceda a mercados europeus e globais com uma plataforma segura, regulamentada e focada nos seus objectivos financeiros.',
    login_reg1: 'Regulamentado pela ESMA e CySEC',
    login_reg2: 'Encriptação SSL de 256 bits',
    login_reg3: 'Operações em tempo real',
    // ── Register ──────────────────────────────────────────────
    reg_title: 'Criar Conta',
    reg_name: 'Nome Completo',
    reg_email: 'E-mail',
    reg_password: 'Palavra-Passe',
    reg_country: 'País',
    reg_btn: 'Criar Conta',
    reg_loading: 'A criar conta…',
    reg_have_account: 'Já tem conta?',
    reg_login: 'Iniciar sessão',
    // ── Nav ───────────────────────────────────────────────────
    nav_trade: 'Negociar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Levantamento',
    nav_history: 'Histórico',
    nav_news: 'Notícias',
    nav_profile: 'Perfil',
    nav_logout: 'Sair',
    nav_balance: 'Saldo',
    nav_profit: 'Lucro',
    nav_total_balance: 'Saldo Total',
    // ── Trade ─────────────────────────────────────────────────
    trade_title: 'Negociar',
    trade_subtitle: 'Mercados globais em tempo real',
    trade_buy: 'COMPRAR',
    trade_sell: 'VENDER',
    trade_instrument: 'Instrumento',
    trade_amount: 'Montante (€)',
    trade_leverage: 'Alavancagem',
    trade_direction: 'Direcção',
    trade_price: 'Preço actual',
    trade_exposure: 'Exposição',
    trade_open_btn: 'Abrir Operação',
    trade_close_btn: 'Encerrar Operação',
    trade_processing: 'A processar…',
    trade_success_open: 'Operação aberta com sucesso',
    trade_success_close: 'Operação encerrada com sucesso',
    trade_invalid_amount: 'Montante inválido',
    trade_min_amount: 'Mínimo €10,00.',
    trade_order_opened: '✓ Operação Aberta',
    trade_order_closed: '✓ Operação Encerrada',
    trade_forex_quotes: 'Cotações Forex',
    trade_search: 'Pesquisar…',
    trade_no_results: 'Sem resultados',
    trade_deposit_btn: 'Depósito',
    trade_withdrawal_btn: 'Levantamento',
    trade_reg_info: 'Plataforma regulamentada pela CySEC · MiFID II · Fundos protegidos ICF',
    // ── Deposit ───────────────────────────────────────────────
    dep_title: 'Depósito',
    dep_subtitle: 'Adicione fundos à sua conta',
    dep_processing: 'Processando depósito…',
    dep_success: 'Depósito enviado! A equipa irá processar em breve.',
    dep_cardholder: 'Nome do Titular',
    dep_card_number: 'Número do Cartão',
    dep_expiry: 'Validade (MM/AA)',
    dep_cvv: 'CVV',
    dep_country: 'País',
    dep_postal: 'Código Postal',
    dep_amount: 'Montante (€)',
    dep_btn: 'Depositar',
    dep_loading: 'A processar…',
    // ── Withdrawal ────────────────────────────────────────────
    wd_title: 'Levantamento',
    wd_subtitle: 'Solicite a retirada dos seus fundos',
    wd_sepa: 'Transferência Bancária (SEPA)',
    wd_card: 'Estorno no Cartão',
    wd_holder: 'Nome do Titular',
    wd_iban: 'IBAN',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Montante (€)',
    wd_btn: 'Solicitar Levantamento',
    wd_processing: 'A processar…',
    wd_success: 'Pedido enviado com sucesso!',
    // ── Profile ───────────────────────────────────────────────
    profile_title: 'O Meu Perfil',
    profile_subtitle: 'Gere os dados da sua conta',
    profile_fullname: 'Nome Completo',
    profile_email: 'Endereço de E-mail',
    profile_phone: 'Número de Telemóvel',
    profile_country: 'País de Residência',
    profile_save: 'Guardar Alterações',
    profile_saving: 'A guardar…',
    profile_saved: 'Perfil actualizado com sucesso!',
    profile_account: 'Resumo da Conta',
    profile_balance: 'Saldo disponível',
    profile_profit: 'Lucro acumulado',
    profile_status: 'Estado da conta',
    profile_member: 'Membro desde',
    profile_indicators: 'Indicadores',
    profile_return: 'Rendimento total',
    profile_security: 'Nível de segurança',
    profile_change_pw: 'Alterar Palavra-passe',
    kyc_title: 'Verificação de Identidade (KYC)',
    kyc_subtitle: 'Envie o seu documento para activar saques completos',
    kyc_verified: 'Verificado',
    kyc_pending: 'Em revisão',
    kyc_rejected: 'Rejeitado',
    kyc_doc_type: 'Tipo de Documento',
    kyc_file: 'Ficheiro (PDF, JPG, PNG — máx. 10 MB)',
    kyc_click: 'Clique para seleccionar ficheiro',
    kyc_uploading: 'A enviar…',
    kyc_success: 'Documento enviado com sucesso!',
    kyc_review: 'A equipa irá rever em breve.',
    kyc_already_sent: 'Documento já enviado — aguarda revisão',
    kyc_verified_msg: 'Identidade verificada com sucesso',
    kyc_verified_sub: 'A sua conta tem acesso completo a todos os serviços.',
    kyc_bi: 'Bilhete de Identidade / CC',
    kyc_passport: 'Passaporte',
    kyc_driver: 'Carta de Condução',
    kyc_proof: 'Comprovativo de Morada',
    // ── History ───────────────────────────────────────────────
    hist_title: 'Histórico de Ordens',
    hist_subtitle: 'Todas as suas operações registadas',
    hist_refresh: 'Actualizar',
    hist_loading: 'A carregar histórico…',
    hist_empty_title: 'Nenhuma operação registada',
    hist_empty_sub: 'As suas ordens aparecerão aqui após negociar.',
    hist_instrument: 'Instrumento',
    hist_side: 'Lado',
    hist_amount: 'Montante',
    hist_leverage: 'Alavancagem',
    hist_exposure: 'Exposição',
    hist_price: 'Preço',
    hist_date: 'Data / Hora',
    hist_buy: 'Compra',
    hist_sell: 'Venda',
    // ── Footer ────────────────────────────────────────────────
    footer_desc: 'Plataforma de investimento premium regulamentada pela CySEC e MiFID II. Oferecemos acesso a mercados globais com total transparência.',
    footer_links: 'Links Rápidos',
    footer_legal: 'Avisos Legais',
    footer_risk: 'Aviso de Risco',
    footer_privacy: 'Política de Privacidade',
    footer_terms: 'Termos de Serviço',
    footer_aml: 'Política AML/KYC',
    footer_contact: 'Contacto',
    footer_support: 'Suporte',
    footer_rights: 'Todos os direitos reservados.',
    footer_risk_text: 'Os CFDs são instrumentos complexos e apresentam um elevado risco de perda rápida de dinheiro. Certifique-se de que compreende como funcionam os CFDs antes de investir.',
    footer_reg: 'Regulamentado CySEC Lic. nº 409/22 · MiFID II · ICF',
    // ── Chat ──────────────────────────────────────────────────
    chat_support: 'Suporte EuroVault',
    chat_online: '● Online',
    chat_placeholder: 'Escreva uma mensagem…',
    chat_send: 'Enviar',
    chat_empty: 'Envie uma mensagem.\nRespondemos rapidamente.',
    // ── General ───────────────────────────────────────────────
    active: 'Activa',
    security_2fa: '2FA activo',
    lang_label: 'Idioma',
    // ── News ──────────────────────────────────────────────────
    news_title: 'Notícias',
    news_subtitle: 'Últimas notícias dos mercados financeiros',
    news_loading: 'A carregar notícias…',
    news_empty: 'Sem notícias disponíveis de momento.',
    news_read: 'Ler mais',
    // ── Register extra ────────────────────────────────────────
    reg_name_ph: 'João Silva',
    reg_email_ph: 'o_seu_email@exemplo.pt',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Crie a sua conta gratuita e comece a investir',
    reg_terms: 'Ao criar conta aceita os nossos Termos de Serviço e Política de Privacidade.',
    // ── Deposit extra ─────────────────────────────────────────
    dep_title_full: 'Depósito de Fundos',
    dep_subtitle_full: 'Adicione fundos de forma segura à sua conta EuroVault',
    dep_card_info: 'Os seus dados de pagamento são encriptados com SSL de 256 bits.',
    dep_confirm_btn: 'Confirmar Depósito',
    dep_processing_msg: 'A processar o seu depósito…',
    dep_success_msg: 'Depósito enviado com sucesso! A nossa equipa irá processar em breve.',
    dep_why_title: 'Porquê depositar na EuroVault?',
    dep_secure: 'Transação segura',
    dep_fast: 'Processamento rápido',
    dep_support: 'Suporte 24/7',
    dep_min: 'Mínimo €10',
    dep_amount_hint: 'Montante mínimo: €10.00',
    dep_popular: 'Popular',
    dep_summary: 'Resumo do Depósito',
    dep_amount_label: 'Montante',
    dep_fee: 'Taxa',
    dep_fee_val: 'Gratuito',
    dep_total: 'Total a creditar',
    dep_secure_badge: 'Pagamento 100% Seguro · SSL 256-bit · PCI DSS',
    // ── Withdrawal extra ──────────────────────────────────────
    wd_title_full: 'Levantamento de Fundos',
    wd_subtitle_full: 'Escolha o método de levantamento',
    wd_tab_sepa: 'Transferência SEPA',
    wd_tab_card: 'Estorno no Cartão',
    wd_sepa_info: 'Transferência SEPA (IBAN) — prazo típico 1–2 dias úteis',
    wd_note: 'Nota (opcional)',
    wd_note_ph: 'Referência ou nota adicional...',
    wd_confirm: 'Confirmar Transferência SEPA',
    wd_loading_btn: 'A enviar...',
    wd_cb_alert: 'Estorno será devolvido ao cartão original do depósito',
    wd_cb_how: 'Como funciona o estorno?',
    wd_cb_step1: 'O pedido é submetido à nossa equipa financeira',
    wd_cb_step2: 'Verificamos o histórico de depósitos da sua conta',
    wd_cb_step3: 'O montante é devolvido ao cartão de crédito/débito original',
    wd_cb_step4: 'Prazo: 5-10 dias úteis (dependendo do banco emissor)',
    wd_cb_btn: 'Iniciar Pedido de Estorno',
    wd_cb_submitted_title: 'Pedido Enviado!',
    wd_cb_submitted_msg: 'O seu pedido de estorno foi registado. A nossa equipa entrará em contacto dentro de 2-3 dias úteis.',
    wd_info_available: 'Saldo disponível para levantamento',
    wd_info_sepa: 'Prazo SEPA',
    wd_info_sepa_val: '1-2 dias úteis',
    wd_info_min: 'Montante mínimo',
    wd_info_min_val: '€10.00',
    wd_info_fee: 'Taxa de levantamento',
    wd_info_fee_val: 'Grátis',
    wd_info_limit: 'Limite diário',
    wd_info_no_limit: 'Sem limite',
    // ── History extra ─────────────────────────────────────────
    hist_no_orders: 'Nenhuma operação registada',
    hist_no_orders_sub: 'As suas ordens aparecerão aqui após negociar.',
    wd_holder: 'Nome do Titular',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Montante',
  },

  en: {
    login_title: 'Sign In',
    login_subtitle: 'Welcome. Enter your credentials to access your account.',
    login_email: 'Email Address',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_loading: 'Signing in…',
    login_no_account: "Don't have an account?",
    login_create: 'Create free account',
    login_secure: 'Secure and encrypted connection. Your data is protected.',
    login_hero1: 'Invest with',
    login_hero2: 'EuroVault',
    login_desc: 'Access European and global markets with a secure, regulated platform focused on your financial goals.',
    login_reg1: 'Regulated by ESMA and CySEC',
    login_reg2: '256-bit SSL Encryption',
    login_reg3: 'Real-time trading',
    reg_title: 'Create Account',
    reg_name: 'Full Name',
    reg_email: 'Email',
    reg_password: 'Password',
    reg_country: 'Country',
    reg_btn: 'Create Account',
    reg_loading: 'Creating account…',
    reg_have_account: 'Already have an account?',
    reg_login: 'Sign in',
    nav_trade: 'Trade',
    nav_deposit: 'Deposit',
    nav_withdrawal: 'Withdrawal',
    nav_history: 'History',
    nav_news: 'News',
    nav_profile: 'Profile',
    nav_logout: 'Sign Out',
    nav_balance: 'Balance',
    nav_profit: 'Profit',
    nav_total_balance: 'Total Balance',
    trade_title: 'Trade',
    trade_subtitle: 'Global markets in real time',
    trade_buy: 'BUY',
    trade_sell: 'SELL',
    trade_instrument: 'Instrument',
    trade_amount: 'Amount (€)',
    trade_leverage: 'Leverage',
    trade_direction: 'Direction',
    trade_price: 'Current price',
    trade_exposure: 'Exposure',
    trade_open_btn: 'Open Trade',
    trade_close_btn: 'Close Trade',
    trade_processing: 'Processing…',
    trade_success_open: 'Trade opened successfully',
    trade_success_close: 'Trade closed successfully',
    trade_invalid_amount: 'Invalid amount',
    trade_min_amount: 'Minimum €10.00.',
    trade_order_opened: '✓ Trade Opened',
    trade_order_closed: '✓ Trade Closed',
    trade_forex_quotes: 'Forex Quotes',
    trade_search: 'Search…',
    trade_no_results: 'No results',
    trade_deposit_btn: 'Deposit',
    trade_withdrawal_btn: 'Withdrawal',
    trade_reg_info: 'Regulated by CySEC · MiFID II · ICF protected funds',
    dep_title: 'Deposit',
    dep_subtitle: 'Add funds to your account',
    dep_processing: 'Processing deposit…',
    dep_success: 'Deposit submitted! Our team will process it shortly.',
    dep_cardholder: 'Cardholder Name',
    dep_card_number: 'Card Number',
    dep_expiry: 'Expiry (MM/YY)',
    dep_cvv: 'CVV',
    dep_country: 'Country',
    dep_postal: 'Postal Code',
    dep_amount: 'Amount (€)',
    dep_btn: 'Deposit',
    dep_loading: 'Processing…',
    wd_title: 'Withdrawal',
    wd_subtitle: 'Request a withdrawal of your funds',
    wd_sepa: 'Bank Transfer (SEPA)',
    wd_card: 'Card Refund',
    wd_holder: 'Account Holder',
    wd_iban: 'IBAN',
    wd_bic: 'BIC/SWIFT Code',
    wd_amount: 'Amount (€)',
    wd_btn: 'Request Withdrawal',
    wd_processing: 'Processing…',
    wd_success: 'Request submitted successfully!',
    profile_title: 'My Profile',
    profile_subtitle: 'Manage your account details',
    profile_fullname: 'Full Name',
    profile_email: 'Email Address',
    profile_phone: 'Phone Number',
    profile_country: 'Country of Residence',
    profile_save: 'Save Changes',
    profile_saving: 'Saving…',
    profile_saved: 'Profile updated successfully!',
    profile_account: 'Account Summary',
    profile_balance: 'Available balance',
    profile_profit: 'Accumulated profit',
    profile_status: 'Account status',
    profile_member: 'Member since',
    profile_indicators: 'Indicators',
    profile_return: 'Total return',
    profile_security: 'Security level',
    profile_change_pw: 'Change Password',
    kyc_title: 'Identity Verification (KYC)',
    kyc_subtitle: 'Submit your document to enable full withdrawals',
    kyc_verified: 'Verified',
    kyc_pending: 'Under Review',
    kyc_rejected: 'Rejected',
    kyc_doc_type: 'Document Type',
    kyc_file: 'File (PDF, JPG, PNG — max. 10 MB)',
    kyc_click: 'Click to select file',
    kyc_uploading: 'Uploading…',
    kyc_success: 'Document submitted successfully!',
    kyc_review: 'Our team will review it shortly.',
    kyc_already_sent: 'Document already submitted — awaiting review',
    kyc_verified_msg: 'Identity verified successfully',
    kyc_verified_sub: 'Your account has full access to all services.',
    kyc_bi: 'National ID / Citizen Card',
    kyc_passport: 'Passport',
    kyc_driver: "Driver's License",
    kyc_proof: 'Proof of Address',
    hist_title: 'Order History',
    hist_subtitle: 'All your recorded trades',
    hist_refresh: 'Refresh',
    hist_loading: 'Loading history…',
    hist_empty_title: 'No orders recorded',
    hist_empty_sub: 'Your orders will appear here after trading.',
    hist_instrument: 'Instrument',
    hist_side: 'Side',
    hist_amount: 'Amount',
    hist_leverage: 'Leverage',
    hist_exposure: 'Exposure',
    hist_price: 'Price',
    hist_date: 'Date / Time',
    hist_buy: 'Buy',
    hist_sell: 'Sell',
    footer_desc: 'Premium investment platform regulated by CySEC and MiFID II. We offer access to global markets with full transparency.',
    footer_links: 'Quick Links',
    footer_legal: 'Legal Notices',
    footer_risk: 'Risk Warning',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_aml: 'AML/KYC Policy',
    footer_contact: 'Contact',
    footer_support: 'Support',
    footer_rights: 'All rights reserved.',
    footer_risk_text: 'CFDs are complex instruments and carry a high risk of rapid money loss. Make sure you understand how CFDs work before investing.',
    footer_reg: 'Regulated CySEC Lic. No. 409/22 · MiFID II · ICF',
    chat_support: 'EuroVault Support',
    chat_online: '● Online',
    chat_placeholder: 'Write a message…',
    chat_send: 'Send',
    chat_empty: 'Send a message.\nWe respond quickly.',
    active: 'Active',
    security_2fa: '2FA active',
    lang_label: 'Language',
    news_title: 'News',
    news_subtitle: 'Latest financial market news',
    news_loading: 'Loading news…',
    news_empty: 'No news available at the moment.',
    news_read: 'Read more',
    reg_name_ph: 'John Smith',
    reg_email_ph: 'your_email@example.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Create your free account and start investing',
    reg_terms: 'By creating an account you agree to our Terms of Service and Privacy Policy.',
    dep_title_full: 'Fund Deposit',
    dep_subtitle_full: 'Securely add funds to your EuroVault account',
    dep_card_info: 'Your payment data is encrypted with 256-bit SSL.',
    dep_confirm_btn: 'Confirm Deposit',
    dep_processing_msg: 'Processing your deposit…',
    dep_success_msg: 'Deposit submitted successfully! Our team will process it shortly.',
    dep_why_title: 'Why deposit at EuroVault?',
    dep_secure: 'Secure transaction',
    dep_fast: 'Fast processing',
    dep_support: 'Support 24/7',
    dep_min: 'Minimum €10',
    dep_amount_hint: 'Minimum amount: €10.00',
    dep_popular: 'Popular',
    dep_summary: 'Deposit Summary',
    dep_amount_label: 'Amount',
    dep_fee: 'Fee',
    dep_fee_val: 'Free',
    dep_total: 'Total to credit',
    dep_secure_badge: '100% Secure Payment · SSL 256-bit · PCI DSS',
    wd_title_full: 'Fund Withdrawal',
    wd_subtitle_full: 'Choose your withdrawal method',
    wd_tab_sepa: 'SEPA Transfer',
    wd_tab_card: 'Card Refund',
    wd_sepa_info: 'SEPA Transfer (IBAN) — typical processing 1–2 business days',
    wd_note: 'Note (optional)',
    wd_note_ph: 'Reference or additional note...',
    wd_confirm: 'Confirm SEPA Transfer',
    wd_loading_btn: 'Sending...',
    wd_cb_alert: 'Refund will be returned to the original deposit card',
    wd_cb_how: 'How does the refund work?',
    wd_cb_step1: 'The request is submitted to our financial team',
    wd_cb_step2: 'We verify your account deposit history',
    wd_cb_step3: 'The amount is returned to the original credit/debit card',
    wd_cb_step4: 'Timeline: 5-10 business days (depending on the issuing bank)',
    wd_cb_btn: 'Start Refund Request',
    wd_cb_submitted_title: 'Request Submitted!',
    wd_cb_submitted_msg: 'Your refund request has been registered. Our team will contact you within 2-3 business days.',
    wd_info_available: 'Available balance',
    wd_info_sepa: 'SEPA timeline',
    wd_info_sepa_val: '1-2 business days',
    wd_info_min: 'Minimum amount',
    wd_info_min_val: '€10.00',
    wd_info_fee: 'Withdrawal fee',
    wd_info_fee_val: 'Free',
    wd_info_limit: 'Daily limit',
    wd_info_no_limit: 'No limit',
    hist_no_orders: 'No orders recorded',
    hist_no_orders_sub: 'Your orders will appear here after trading.',
  },

  es: {
    login_title: 'Iniciar Sesión',
    login_subtitle: 'Bienvenido. Introduzca sus credenciales de acceso.',
    login_email: 'Dirección de E-mail',
    login_password: 'Contraseña',
    login_btn: 'Entrar',
    login_loading: 'Iniciando sesión…',
    login_no_account: '¿No tiene cuenta?',
    login_create: 'Crear cuenta gratuita',
    login_secure: 'Conexión segura y cifrada. Sus datos están protegidos.',
    login_hero1: 'Invierta con',
    login_hero2: 'EuroVault',
    login_desc: 'Acceda a mercados europeos y globales con una plataforma segura, regulada y centrada en sus objetivos financieros.',
    login_reg1: 'Regulado por ESMA y CySEC',
    login_reg2: 'Cifrado SSL de 256 bits',
    login_reg3: 'Operaciones en tiempo real',
    reg_title: 'Crear Cuenta',
    reg_name: 'Nombre Completo',
    reg_email: 'E-mail',
    reg_password: 'Contraseña',
    reg_country: 'País',
    reg_btn: 'Crear Cuenta',
    reg_loading: 'Creando cuenta…',
    reg_have_account: '¿Ya tiene cuenta?',
    reg_login: 'Iniciar sesión',
    nav_trade: 'Operar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Retiro',
    nav_history: 'Historial',
    nav_news: 'Noticias',
    nav_profile: 'Perfil',
    nav_logout: 'Salir',
    nav_balance: 'Saldo',
    nav_profit: 'Beneficio',
    nav_total_balance: 'Saldo Total',
    trade_title: 'Operar',
    trade_subtitle: 'Mercados globales en tiempo real',
    trade_buy: 'COMPRAR',
    trade_sell: 'VENDER',
    trade_instrument: 'Instrumento',
    trade_amount: 'Importe (€)',
    trade_leverage: 'Apalancamiento',
    trade_direction: 'Dirección',
    trade_price: 'Precio actual',
    trade_exposure: 'Exposición',
    trade_open_btn: 'Abrir Operación',
    trade_close_btn: 'Cerrar Operación',
    trade_processing: 'Procesando…',
    trade_success_open: 'Operación abierta con éxito',
    trade_success_close: 'Operación cerrada con éxito',
    trade_invalid_amount: 'Importe no válido',
    trade_min_amount: 'Mínimo €10,00.',
    trade_order_opened: '✓ Operación Abierta',
    trade_order_closed: '✓ Operación Cerrada',
    trade_forex_quotes: 'Cotizaciones Forex',
    trade_search: 'Buscar…',
    trade_no_results: 'Sin resultados',
    trade_deposit_btn: 'Depósito',
    trade_withdrawal_btn: 'Retiro',
    trade_reg_info: 'Plataforma regulada por CySEC · MiFID II · Fondos protegidos ICF',
    dep_title: 'Depósito',
    dep_subtitle: 'Añada fondos a su cuenta',
    dep_processing: 'Procesando depósito…',
    dep_success: '¡Depósito enviado! Nuestro equipo lo procesará en breve.',
    dep_cardholder: 'Nombre del Titular',
    dep_card_number: 'Número de Tarjeta',
    dep_expiry: 'Caducidad (MM/AA)',
    dep_cvv: 'CVV',
    dep_country: 'País',
    dep_postal: 'Código Postal',
    dep_amount: 'Importe (€)',
    dep_btn: 'Depositar',
    dep_loading: 'Procesando…',
    wd_title: 'Retiro',
    wd_subtitle: 'Solicite la retirada de sus fondos',
    wd_sepa: 'Transferencia Bancaria (SEPA)',
    wd_card: 'Devolución a la Tarjeta',
    wd_holder: 'Titular de la Cuenta',
    wd_iban: 'IBAN',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Importe (€)',
    wd_btn: 'Solicitar Retiro',
    wd_processing: 'Procesando…',
    wd_success: '¡Solicitud enviada con éxito!',
    profile_title: 'Mi Perfil',
    profile_subtitle: 'Gestione los datos de su cuenta',
    profile_fullname: 'Nombre Completo',
    profile_email: 'Dirección de E-mail',
    profile_phone: 'Número de Teléfono',
    profile_country: 'País de Residencia',
    profile_save: 'Guardar Cambios',
    profile_saving: 'Guardando…',
    profile_saved: '¡Perfil actualizado con éxito!',
    profile_account: 'Resumen de Cuenta',
    profile_balance: 'Saldo disponible',
    profile_profit: 'Beneficio acumulado',
    profile_status: 'Estado de la cuenta',
    profile_member: 'Miembro desde',
    profile_indicators: 'Indicadores',
    profile_return: 'Rendimiento total',
    profile_security: 'Nivel de seguridad',
    profile_change_pw: 'Cambiar Contraseña',
    kyc_title: 'Verificación de Identidad (KYC)',
    kyc_subtitle: 'Envíe su documento para activar retiros completos',
    kyc_verified: 'Verificado',
    kyc_pending: 'En revisión',
    kyc_rejected: 'Rechazado',
    kyc_doc_type: 'Tipo de Documento',
    kyc_file: 'Archivo (PDF, JPG, PNG — máx. 10 MB)',
    kyc_click: 'Haga clic para seleccionar archivo',
    kyc_uploading: 'Subiendo…',
    kyc_success: '¡Documento enviado con éxito!',
    kyc_review: 'Nuestro equipo lo revisará en breve.',
    kyc_already_sent: 'Documento ya enviado — pendiente de revisión',
    kyc_verified_msg: 'Identidad verificada con éxito',
    kyc_verified_sub: 'Su cuenta tiene acceso completo a todos los servicios.',
    kyc_bi: 'DNI / Tarjeta de Ciudadano',
    kyc_passport: 'Pasaporte',
    kyc_driver: 'Permiso de Conducir',
    kyc_proof: 'Justificante de Domicilio',
    hist_title: 'Historial de Órdenes',
    hist_subtitle: 'Todas sus operaciones registradas',
    hist_refresh: 'Actualizar',
    hist_loading: 'Cargando historial…',
    hist_empty_title: 'Ninguna operación registrada',
    hist_empty_sub: 'Sus órdenes aparecerán aquí después de operar.',
    hist_instrument: 'Instrumento',
    hist_side: 'Lado',
    hist_amount: 'Importe',
    hist_leverage: 'Apalancamiento',
    hist_exposure: 'Exposición',
    hist_price: 'Precio',
    hist_date: 'Fecha / Hora',
    hist_buy: 'Compra',
    hist_sell: 'Venta',
    footer_desc: 'Plataforma de inversión premium regulada por CySEC y MiFID II. Ofrecemos acceso a mercados globales con total transparencia.',
    footer_links: 'Enlaces Rápidos',
    footer_legal: 'Avisos Legales',
    footer_risk: 'Aviso de Riesgo',
    footer_privacy: 'Política de Privacidad',
    footer_terms: 'Términos de Servicio',
    footer_aml: 'Política AML/KYC',
    footer_contact: 'Contacto',
    footer_support: 'Soporte',
    footer_rights: 'Todos los derechos reservados.',
    footer_risk_text: 'Los CFDs son instrumentos complejos y conllevan un alto riesgo de pérdida rápida de dinero. Asegúrese de entender cómo funcionan los CFDs antes de invertir.',
    footer_reg: 'Regulado CySEC Lic. nº 409/22 · MiFID II · ICF',
    chat_support: 'Soporte EuroVault',
    chat_online: '● En línea',
    chat_placeholder: 'Escriba un mensaje…',
    chat_send: 'Enviar',
    chat_empty: 'Envíe un mensaje.\nRespondemos rápido.',
    active: 'Activa',
    security_2fa: '2FA activo',
    lang_label: 'Idioma',
    news_title: 'Noticias',
    news_subtitle: 'Últimas noticias de los mercados financieros',
    news_loading: 'Cargando noticias…',
    news_empty: 'Sin noticias disponibles por el momento.',
    news_read: 'Leer más',
    reg_name_ph: 'Juan García',
    reg_email_ph: 'su_email@ejemplo.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Cree su cuenta gratuita y comience a invertir',
    reg_terms: 'Al crear una cuenta acepta nuestros Términos de Servicio y Política de Privacidad.',
    dep_title_full: 'Depósito de Fondos',
    dep_subtitle_full: 'Añada fondos de forma segura a su cuenta EuroVault',
    dep_card_info: 'Sus datos de pago están cifrados con SSL de 256 bits.',
    dep_confirm_btn: 'Confirmar Depósito',
    dep_processing_msg: 'Procesando su depósito…',
    dep_success_msg: '¡Depósito enviado con éxito! Nuestro equipo lo procesará en breve.',
    dep_why_title: '¿Por qué depositar en EuroVault?',
    dep_secure: 'Transacción segura',
    dep_fast: 'Procesamiento rápido',
    dep_support: 'Soporte 24/7',
    dep_min: 'Mínimo €10',
    dep_amount_hint: 'Importe mínimo: €10,00',
    dep_popular: 'Popular',
    dep_summary: 'Resumen del Depósito',
    dep_amount_label: 'Importe',
    dep_fee: 'Tarifa',
    dep_fee_val: 'Gratis',
    dep_total: 'Total a acreditar',
    dep_secure_badge: 'Pago 100% Seguro · SSL 256-bit · PCI DSS',
    wd_title_full: 'Retiro de Fondos',
    wd_subtitle_full: 'Elija su método de retiro',
    wd_tab_sepa: 'Transferencia SEPA',
    wd_tab_card: 'Devolución a Tarjeta',
    wd_sepa_info: 'Transferencia SEPA (IBAN) — plazo típico 1–2 días hábiles',
    wd_note: 'Nota (opcional)',
    wd_note_ph: 'Referencia o nota adicional...',
    wd_confirm: 'Confirmar Transferencia SEPA',
    wd_loading_btn: 'Enviando...',
    wd_cb_alert: 'El reembolso se devolverá a la tarjeta de depósito original',
    wd_cb_how: '¿Cómo funciona el reembolso?',
    wd_cb_step1: 'La solicitud se envía a nuestro equipo financiero',
    wd_cb_step2: 'Verificamos el historial de depósitos de su cuenta',
    wd_cb_step3: 'El importe se devuelve a la tarjeta de crédito/débito original',
    wd_cb_step4: 'Plazo: 5-10 días hábiles (según el banco emisor)',
    wd_cb_btn: 'Iniciar Solicitud de Reembolso',
    wd_cb_submitted_title: '¡Solicitud Enviada!',
    wd_cb_submitted_msg: 'Su solicitud de reembolso ha sido registrada. Nuestro equipo le contactará en 2-3 días hábiles.',
    wd_info_available: 'Saldo disponible',
    wd_info_sepa: 'Plazo SEPA',
    wd_info_sepa_val: '1-2 días hábiles',
    wd_info_min: 'Importe mínimo',
    wd_info_min_val: '€10,00',
    wd_info_fee: 'Tarifa de retiro',
    wd_info_fee_val: 'Gratis',
    wd_info_limit: 'Límite diario',
    wd_info_no_limit: 'Sin límite',
    hist_no_orders: 'Ninguna operación registrada',
    hist_no_orders_sub: 'Sus órdenes aparecerán aquí después de operar.',
  },
};

// ─────────────────────────────────────────────────────────────
//  Contexto
// ─────────────────────────────────────────────────────────────
const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('ev_lang') || 'pt';
  });

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('ev_lang', newLang);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['pt']?.[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
