import React, { createContext, useContext, useState } from 'react';

// ─────────────────────────────────────────────────────────────
//  Dicionário de traduções
// ─────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  pt: {
    // ── Auth ──────────────────────────────────────────────────
    login_title: 'Iniciar Sessão',
    login_subtitle: 'Bem-vindo. Introduza as suas credenciais de acesso.',
    login_email: 'Endereço de E-mail',
    login_email_ph: 'exemplo@gmail.com',
    login_password: 'Palavra-Passe',
    login_btn: 'Entrar',
    login_loading: 'A entrar…',
    login_no_account: 'Não tem conta?',
    login_create: 'Criar conta gratuita',
    login_secure: 'Ligação segura e encriptada. Os seus dados estão protegidos.',
    login_hero1: 'Invista com',
    login_hero2: 'EuroVault',
    login_desc: 'Aceda a mercados europeus e globais com uma plataforma segura, regulamentada e focada nos seus objectivos financeiros.',
    login_reg1: 'Regulamentado pela ESMA e CySEC',
    login_reg2: 'Encriptação SSL de 256 bits',
    login_reg3: 'Operações em tempo real',
    // ── Register ──────────────────────────────────────────────
    reg_title: 'Criar Conta',
    reg_name: 'Nome Completo',
    reg_email: 'E-mail',
    reg_password: 'Palavra-Passe',
    reg_country: 'País',
    reg_btn: 'Criar Conta',
    reg_loading: 'A criar conta…',
    reg_have_account: 'Já tem conta?',
    reg_login: 'Iniciar sessão',
    // ── Nav ───────────────────────────────────────────────────
    nav_trade: 'Negociar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Levantamento',
    nav_history: 'Histórico',
    nav_news: 'Notícias',
    nav_profile: 'Perfil',
    nav_logout: 'Sair',
    nav_balance: 'Saldo',
    nav_profit: 'Lucro',
    nav_total_balance: 'Saldo Total',
    // ── Trade ─────────────────────────────────────────────────
    trade_title: 'Negociar',
    trade_subtitle: 'Mercados globais em tempo real',
    trade_buy: 'COMPRAR',
    trade_sell: 'VENDER',
    trade_instrument: 'Instrumento',
    trade_amount: 'Montante (€)',
    trade_leverage: 'Alavancagem',
    trade_direction: 'Direcção',
    trade_price: 'Preço actual',
    trade_exposure: 'Exposição',
    trade_open_btn: 'Abrir Operação',
    trade_close_btn: 'Encerrar Operação',
    trade_processing: 'A processar…',
    trade_success_open: 'Operação aberta com sucesso',
    trade_success_close: 'Operação encerrada com sucesso',
    trade_invalid_amount: 'Montante inválido',
    trade_min_amount: 'Mínimo €10,00.',
    trade_order_opened: '✓ Operação Aberta',
    trade_order_closed: '✓ Operação Encerrada',
    trade_forex_quotes: 'Cotações Forex',
    trade_search: 'Pesquisar…',
    trade_no_results: 'Sem resultados',
    trade_deposit_btn: 'Depósito',
    trade_withdrawal_btn: 'Levantamento',
    trade_reg_info: 'Plataforma regulamentada pela CySEC · MiFID II · Fundos protegidos ICF',
    // ── Deposit ───────────────────────────────────────────────
    dep_title: 'Depósito',
    dep_subtitle: 'Adicione fundos à sua conta',
    dep_processing: 'Processando depósito…',
    dep_success: 'Depósito enviado! A equipa irá processar em breve.',
    dep_cardholder: 'Nome do Titular',
    dep_card_number: 'Número do Cartão',
    dep_expiry: 'Validade (MM/AA)',
    dep_cvv: 'CVV',
    dep_country: 'País',
    dep_postal: 'Código Postal',
    dep_amount: 'Montante (€)',
    dep_btn: 'Depositar',
    dep_loading: 'A processar…',
    // ── Withdrawal ────────────────────────────────────────────
    wd_title: 'Levantamento',
    wd_subtitle: 'Solicite a retirada dos seus fundos',
    wd_sepa: 'Transferência Bancária (SEPA)',
    wd_card: 'Estorno no Cartão',
    wd_holder: 'Nome do Titular',
    wd_iban: 'IBAN',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Montante (€)',
    wd_btn: 'Solicitar Levantamento',
    wd_processing: 'A processar…',
    wd_success: 'Pedido enviado com sucesso!',
    // ── Profile ───────────────────────────────────────────────
    profile_title: 'O Meu Perfil',
    profile_subtitle: 'Gere os dados da sua conta',
    profile_fullname: 'Nome Completo',
    profile_email: 'Endereço de E-mail',
    profile_phone: 'Número de Telemóvel',
    profile_country: 'País de Residência',
    profile_save: 'Guardar Alterações',
    profile_saving: 'A guardar…',
    profile_saved: 'Perfil actualizado com sucesso!',
    profile_account: 'Resumo da Conta',
    profile_balance: 'Saldo disponível',
    profile_profit: 'Lucro acumulado',
    profile_status: 'Estado da conta',
    profile_member: 'Membro desde',
    profile_indicators: 'Indicadores',
    profile_return: 'Rendimento total',
    profile_security: 'Nível de segurança',
    profile_change_pw: 'Alterar Palavra-passe',
    kyc_title: 'Verificação de Identidade (KYC)',
    kyc_subtitle: 'Envie o seu documento para activar saques completos',
    kyc_verified: 'Verificado',
    kyc_pending: 'Em revisão',
    kyc_rejected: 'Rejeitado',
    kyc_doc_type: 'Tipo de Documento',
    kyc_file: 'Ficheiro (PDF, JPG, PNG — máx. 10 MB)',
    kyc_click: 'Clique para seleccionar ficheiro',
    kyc_uploading: 'A enviar…',
    kyc_success: 'Documento enviado com sucesso!',
    kyc_review: 'A equipa irá rever em breve.',
    kyc_already_sent: 'Documento já enviado — aguarda revisão',
    kyc_verified_msg: 'Identidade verificada com sucesso',
    kyc_verified_sub: 'A sua conta tem acesso completo a todos os serviços.',
    kyc_bi: 'Bilhete de Identidade / CC',
    kyc_passport: 'Passaporte',
    kyc_driver: 'Carta de Condução',
    kyc_proof: 'Comprovativo de Morada',
    // ── History ───────────────────────────────────────────────
    hist_title: 'Histórico de Ordens',
    hist_subtitle: 'Todas as suas operações registadas',
    hist_refresh: 'Actualizar',
    hist_loading: 'A carregar histórico…',
    hist_empty_title: 'Nenhuma operação registada',
    hist_empty_sub: 'As suas ordens aparecerão aqui após negociar.',
    hist_instrument: 'Instrumento',
    hist_side: 'Lado',
    hist_amount: 'Montante',
    hist_leverage: 'Alavancagem',
    hist_exposure: 'Exposição',
    hist_price: 'Preço',
    hist_date: 'Data / Hora',
    hist_buy: 'Compra',
    hist_sell: 'Venda',
    // ── Footer ────────────────────────────────────────────────
    footer_desc: 'Plataforma de investimento premium regulamentada pela CySEC e MiFID II. Oferecemos acesso a mercados globais com total transparência.',
    footer_links: 'Links Rápidos',
    footer_legal: 'Avisos Legais',
    footer_risk: 'Aviso de Risco',
    footer_privacy: 'Política de Privacidade',
    footer_terms: 'Termos de Serviço',
    footer_aml: 'Política AML/KYC',
    footer_contact: 'Contacto',
    footer_support: 'Suporte',
    footer_rights: 'Todos os direitos reservados.',
    footer_risk_text: 'Os CFDs são instrumentos complexos e apresentam um elevado risco de perda rápida de dinheiro. Certifique-se de que compreende como funcionam os CFDs antes de investir.',
    footer_reg: 'Regulamentado CySEC Lic. nº 409/22 · MiFID II · ICF',
    // ── Chat ──────────────────────────────────────────────────
    chat_support: 'Suporte EuroVault',
    chat_online: '● Online',
    chat_placeholder: 'Escreva uma mensagem…',
    chat_send: 'Enviar',
    chat_empty: 'Envie uma mensagem.\nRespondemos rapidamente.',
    // ── General ───────────────────────────────────────────────
    active: 'Activa',
    security_2fa: '2FA activo',
    lang_label: 'Idioma',
    // ── Dashboard ─────────────────────────────────────────────
    dash_good_morning: 'Bom dia',
    dash_good_afternoon: 'Boa tarde',
    dash_good_evening: 'Boa noite',
    dash_subtitle: 'Aqui está o resumo da sua conta',
    dash_quick_actions: 'Acções Rápidas',
    dash_recent_activity: 'Actividades Recentes',
    dash_no_activity: 'Sem actividades ainda.\nComece por fazer um depósito.',
    dash_account_status: 'Estado da Conta',
    dash_kyc_verified: '✓ Identidade Verificada',
    dash_kyc_verified_sub: 'Acesso completo à plataforma',
    dash_kyc_pending: 'KYC Pendente',
    dash_kyc_pending_sub: 'Envie os seus documentos',
    dash_verify_now: 'Verificar Agora →',
    dash_available_balance: 'Saldo disponível',
    dash_go_trade: 'Mercados Abertos',
    dash_go_trade_sub: 'Forex · Cripto · Acções · Metais · Commodities',
    dash_live: 'Tempo Real',
    dash_referral: 'Programa de Parceiros',
    dash_referral_guests: 'Convidados',
    dash_referral_bonus: 'Bónus Total',
    dash_see_program: 'Ver Programa Completo',
    dash_daily_profit: 'Lucro Diário',
    dash_profit_not_set: 'Taxa não definida',
    dash_investment_goal: 'Meta de Investimento',
    dash_set_goal: 'Definir Meta de Investimento',
    dash_set_goal_sub: 'Acompanhe o progresso rumo ao seu objetivo',
    // ── Profile ───────────────────────────────────────────────
    prof_goal_title: 'Meta de Investimento',
    prof_goal_sub: 'Define um objetivo e acompanha o progresso',
    prof_goal_name: 'Nome da Meta',
    prof_goal_amount: 'Valor Alvo (€)',
    prof_goal_save: 'Guardar Meta',
    prof_goal_saving: 'A guardar…',
    prof_goal_update: 'Actualizar',
    prof_goal_define: 'Definir Meta',
    prof_goal_edit: 'Editar',
    prof_goal_cancel: 'Cancelar',
    prof_sessions_title: 'Histórico de Sessões',
    prof_sessions_sub: 'Últimos acessos à sua conta',
    prof_sessions_empty: 'Sem sessões registadas ainda.',
    prof_sessions_current: 'Atual',
    prof_change_pw: 'Alterar Palavra-passe',
    prof_account_summary: 'Resumo da Conta',
    prof_member_since: 'Membro desde',
    prof_total_return: 'Rendimento total',
    prof_security_level: 'Nível de segurança',
    // ── News ──────────────────────────────────────────────────
    news_title: 'Notícias',
    news_subtitle: 'Últimas notícias dos mercados financeiros',
    news_loading: 'A carregar notícias…',
    news_empty: 'Sem notícias disponíveis de momento.',
    news_read: 'Ler mais',
    news_realtime: 'Tempo real',
    news_articles: 'artigos',
    news_next_update: 'Próxima actualização em',
    news_refresh: 'Actualizar',
    news_sources: 'Fontes: Reuters · Yahoo Finance · CoinDesk · Investing.com · Auto-refresh a cada 5 minutos',
    news_search_ph: 'Pesquisar notícias em tempo real...',
    news_no_results: 'Nenhuma notícia encontrada',
    // ── Balance history ───────────────────────────────────────
    bal_title: 'Evolução do Saldo',
    bal_subtitle: 'Histórico visual dos últimos 30 dias',
    bal_current: 'Saldo Actual',
    bal_profit: 'Lucro Total',
    bal_change: 'Variação 30d',
    bal_gain: 'Ganho Absoluto',
    bal_chart_title: 'Saldo ao Longo do Tempo',
    bal_history: 'Histórico Detalhado',
    bal_no_data: 'Sem histórico disponível ainda.',
    bal_date: 'Data',
    bal_variation: 'Variação',
    // ── Login stats ───────────────────────────────────────────
    login_stat_volume: 'Volume gerido',
    login_stat_investors: 'Investidores',
    login_stat_uptime: 'Uptime',
    login_stat_support: 'Suporte activo',
    login_badge_live: 'MERCADOS ABERTOS · TEMPO REAL',
    // ── Deposit ───────────────────────────────────────────────
    dep_processing_step2: 'Processamento pelo departamento financeiro',
    dep_processing_step3: 'Crédito na sua conta EuroVault',
    dep_badge_instant: 'Instant',
    dep_why_1: 'Processamento em 1-2h úteis',
    dep_why_2: 'Encriptação SSL 256-bit',
    dep_why_3: 'Regulamentado CySEC & ESMA',
    dep_why_4: 'Visa, Mastercard, Amex, Maestro',
    dep_why_5: 'Suporte 24/7 por chat',
    dep_summary_amount: 'Montante',
    dep_summary_fee: 'Taxa',
    dep_summary_free: 'Gratuito',
    dep_summary_total: 'Total creditado',
    dep_new: 'Novo Depósito',
    dep_success_step1: 'Pedido recebido e validado',
    dep_success_step2: 'Processamento pelo departamento financeiro',
    dep_success_step3: 'Crédito na sua conta EuroVault',
    dep_secure_text: '🔒 Transacção encriptada · SSL 256-bit · PCI DSS Certificado',
    // ── Profile ───────────────────────────────────────────────
    prof_saved: 'Perfil actualizado com sucesso!',
    prof_save_btn: 'Guardar Alterações',
    prof_saving_btn: 'A guardar…',
    prof_member_label: 'Membro desde',
    prof_return_label: 'Rendimento total',
    prof_security_label: 'Nível de segurança',
    prof_2fa_active: '2FA activo',
    prof_personal_data: 'Dados Pessoais', prof_fullname_ph: 'NOME APELIDO',
    // ── Footer ────────────────────────────────────────────────
    footer_platform: 'Plataforma',
    footer_referral: 'Parceiros',
    footer_terms_short: 'Termos',
    footer_privacy_short: 'Privacidade',
    footer_cookies_short: 'Cookies',
    footer_aml_short: 'AML/KYC',
    footer_help: 'Centro de Ajuda',
    footer_faq: 'FAQ — Perguntas Frequentes',
    footer_tutorials: 'Tutoriais de Negociação',
    footer_report: 'Reportar Problema',
    // ── Trade ─────────────────────────────────────────────────
    trade_market_open: '● Mercados Abertos',
    trade_live: 'Tempo Real',
    trade_reg_badge: 'Plataforma regulamentada',
    // ── 404 ───────────────────────────────────────────────────
    page_not_found: 'Página não encontrada',
    page_not_found_sub: 'A página que procura não existe ou foi movida.',
    page_go_home: 'Ir para o Dashboard',
    page_go_login: 'Ir para o Login',
    page_back: 'Voltar',
    // ── Referral ──────────────────────────────────────────────
    ref_title: 'Programa de Parceiros',
    ref_copy: 'Copiar',
    ref_copied: 'Copiado!',
    ref_share: 'Partilhar',
    ref_how_title: 'Como Funciona',
    ref_levels_title: 'Níveis de Parceiro',
    ref_levels_sub: 'Baseado no valor depositado',
    ref_cta: 'Depositar e Subir de Nível',
    // ── Register extra ────────────────────────────────────────
    reg_name_ph: 'João Silva',
    reg_email_ph: 'exemplo@gmail.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Crie a sua conta gratuita e comece a investir',
    reg_terms: 'Ao criar conta aceita os nossos Termos de Serviço e Política de Privacidade.',
    // ── Deposit extra ─────────────────────────────────────────
    dep_title_full: 'Depósito de Fundos',
    dep_subtitle_full: 'Adicione fundos de forma segura à sua conta EuroVault',
    dep_card_info: 'Os seus dados de pagamento são encriptados com SSL de 256 bits.',
    dep_confirm_btn: 'Confirmar Depósito',
    dep_processing_msg: 'A processar o seu depósito…',
    dep_success_msg: 'Depósito enviado com sucesso! A nossa equipa irá processar em breve.',
    dep_why_title: 'Porquê depositar na EuroVault?',
    dep_secure: 'Transação segura',
    dep_fast: 'Processamento rápido',
    dep_support: 'Suporte 24/7',
    dep_min: 'Mínimo €10',
    dep_amount_hint: 'Montante mínimo: €10.00',
    dep_popular: 'Popular',
    dep_summary: 'Resumo do Depósito',
    dep_amount_label: 'Montante',
    dep_fee: 'Taxa',
    dep_fee_val: 'Gratuito',
    dep_total: 'Total a creditar',
    dep_secure_badge: 'Pagamento 100% Seguro · SSL 256-bit · PCI DSS',
    // ── Withdrawal extra ──────────────────────────────────────
    wd_title_full: 'Levantamento de Fundos',
    wd_subtitle_full: 'Escolha o método de levantamento',
    wd_tab_sepa: 'Transferência SEPA',
    wd_tab_card: 'Levantamento para Cartão',
    wd_sepa_info: 'Transferência SEPA (IBAN) — prazo típico 1–2 dias úteis',
    wd_note: 'Nota (opcional)',
    wd_note_ph: 'Referência ou nota adicional...',
    wd_confirm: 'Confirmar Transferência SEPA',
    wd_loading_btn: 'A enviar...',
    wd_card_holder: 'Titular do Cartão',
    wd_card_holder_ph: 'Nome como aparece no cartão',
    wd_card_number: 'Número do Cartão',
    wd_card_number_ph: '•••• •••• •••• ••••',
    wd_card_btn: 'Solicitar Levantamento para Cartão',
    wd_cb_submitted_title: 'Pedido Enviado!',
    wd_cb_submitted_msg: 'O seu pedido foi registado. A nossa equipa entrará em contacto dentro de 2-3 dias úteis.',
    wd_info_available: 'Saldo disponível para levantamento',
    wd_info_sepa: 'Prazo SEPA',
    wd_info_sepa_val: '1-2 dias úteis',
    wd_info_min: 'Montante mínimo',
    wd_info_min_val: '€10.00',
    wd_info_fee: 'Taxa de levantamento',
    wd_info_fee_val: 'Grátis',
    wd_info_limit: 'Limite diário',
    wd_info_no_limit: 'Sem limite',
    // ── History extra ─────────────────────────────────────────
    hist_no_orders: 'Nenhuma operação registada',
    hist_no_orders_sub: 'As suas ordens aparecerão aqui após negociar.',
    wd_holder: 'Nome do Titular',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Montante',
  },

  en: {
    login_title: 'Sign In',
    login_subtitle: 'Welcome. Enter your credentials to access your account.',
    login_email: 'Email Address',
    login_email_ph: 'example@gmail.com',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_loading: 'Signing in…',
    login_no_account: "Don't have an account?",
    login_create: 'Create free account',
    login_secure: 'Secure and encrypted connection. Your data is protected.',
    login_hero1: 'Invest with',
    login_hero2: 'EuroVault',
    login_desc: 'Access European and global markets with a secure, regulated platform focused on your financial goals.',
    login_reg1: 'Regulated by ESMA and CySEC',
    login_reg2: '256-bit SSL Encryption',
    login_reg3: 'Real-time trading',
    reg_title: 'Create Account',
    reg_name: 'Full Name',
    reg_email: 'Email',
    reg_password: 'Password',
    reg_country: 'Country',
    reg_btn: 'Create Account',
    reg_loading: 'Creating account…',
    reg_have_account: 'Already have an account?',
    reg_login: 'Sign in',
    nav_trade: 'Trade',
    nav_deposit: 'Deposit',
    nav_withdrawal: 'Withdrawal',
    nav_history: 'History',
    nav_news: 'News',
    nav_profile: 'Profile',
    nav_logout: 'Sign Out',
    nav_balance: 'Balance',
    nav_profit: 'Profit',
    nav_total_balance: 'Total Balance',
    trade_title: 'Trade',
    trade_subtitle: 'Global markets in real time',
    trade_buy: 'BUY',
    trade_sell: 'SELL',
    trade_instrument: 'Instrument',
    trade_amount: 'Amount (€)',
    trade_leverage: 'Leverage',
    trade_direction: 'Direction',
    trade_price: 'Current price',
    trade_exposure: 'Exposure',
    trade_open_btn: 'Open Trade',
    trade_close_btn: 'Close Trade',
    trade_processing: 'Processing…',
    trade_success_open: 'Trade opened successfully',
    trade_success_close: 'Trade closed successfully',
    trade_invalid_amount: 'Invalid amount',
    trade_min_amount: 'Minimum €10.00.',
    trade_order_opened: '✓ Trade Opened',
    trade_order_closed: '✓ Trade Closed',
    trade_forex_quotes: 'Forex Quotes',
    trade_search: 'Search…',
    trade_no_results: 'No results',
    trade_deposit_btn: 'Deposit',
    trade_withdrawal_btn: 'Withdrawal',
    trade_reg_info: 'Regulated by CySEC · MiFID II · ICF protected funds',
    dep_title: 'Deposit',
    dep_subtitle: 'Add funds to your account',
    dep_processing: 'Processing deposit…',
    dep_success: 'Deposit submitted! Our team will process it shortly.',
    dep_cardholder: 'Cardholder Name',
    dep_card_number: 'Card Number',
    dep_expiry: 'Expiry (MM/YY)',
    dep_cvv: 'CVV',
    dep_country: 'Country',
    dep_postal: 'Postal Code',
    dep_amount: 'Amount (€)',
    dep_btn: 'Deposit',
    dep_loading: 'Processing…',
    wd_title: 'Withdrawal',
    wd_subtitle: 'Request a withdrawal of your funds',
    wd_sepa: 'Bank Transfer (SEPA)',
    wd_card: 'Card Refund',
    wd_holder: 'Account Holder',
    wd_iban: 'IBAN',
    wd_bic: 'BIC/SWIFT Code',
    wd_amount: 'Amount (€)',
    wd_btn: 'Request Withdrawal',
    wd_processing: 'Processing…',
    wd_success: 'Request submitted successfully!',
    profile_title: 'My Profile',
    profile_subtitle: 'Manage your account details',
    profile_fullname: 'Full Name',
    profile_email: 'Email Address',
    profile_phone: 'Phone Number',
    profile_country: 'Country of Residence',
    profile_save: 'Save Changes',
    profile_saving: 'Saving…',
    profile_saved: 'Profile updated successfully!',
    profile_account: 'Account Summary',
    profile_balance: 'Available balance',
    profile_profit: 'Accumulated profit',
    profile_status: 'Account status',
    profile_member: 'Member since',
    profile_indicators: 'Indicators',
    profile_return: 'Total return',
    profile_security: 'Security level',
    profile_change_pw: 'Change Password',
    kyc_title: 'Identity Verification (KYC)',
    kyc_subtitle: 'Submit your document to enable full withdrawals',
    kyc_verified: 'Verified',
    kyc_pending: 'Under Review',
    kyc_rejected: 'Rejected',
    kyc_doc_type: 'Document Type',
    kyc_file: 'File (PDF, JPG, PNG — max. 10 MB)',
    kyc_click: 'Click to select file',
    kyc_uploading: 'Uploading…',
    kyc_success: 'Document submitted successfully!',
    kyc_review: 'Our team will review it shortly.',
    kyc_already_sent: 'Document already submitted — awaiting review',
    kyc_verified_msg: 'Identity verified successfully',
    kyc_verified_sub: 'Your account has full access to all services.',
    kyc_bi: 'National ID / Citizen Card',
    kyc_passport: 'Passport',
    kyc_driver: "Driver's License",
    kyc_proof: 'Proof of Address',
    hist_title: 'Order History',
    hist_subtitle: 'All your recorded trades',
    hist_refresh: 'Refresh',
    hist_loading: 'Loading history…',
    hist_empty_title: 'No orders recorded',
    hist_empty_sub: 'Your orders will appear here after trading.',
    hist_instrument: 'Instrument',
    hist_side: 'Side',
    hist_amount: 'Amount',
    hist_leverage: 'Leverage',
    hist_exposure: 'Exposure',
    hist_price: 'Price',
    hist_date: 'Date / Time',
    hist_buy: 'Buy',
    hist_sell: 'Sell',
    footer_desc: 'Premium investment platform regulated by CySEC and MiFID II. We offer access to global markets with full transparency.',
    footer_links: 'Quick Links',
    footer_legal: 'Legal Notices',
    footer_risk: 'Risk Warning',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_aml: 'AML/KYC Policy',
    footer_contact: 'Contact',
    footer_support: 'Support',
    footer_rights: 'All rights reserved.',
    footer_risk_text: 'CFDs are complex instruments and carry a high risk of rapid money loss. Make sure you understand how CFDs work before investing.',
    footer_reg: 'Regulated CySEC Lic. No. 409/22 · MiFID II · ICF',
    chat_support: 'EuroVault Support',
    chat_online: '● Online',
    chat_placeholder: 'Write a message…',
    chat_send: 'Send',
    chat_empty: 'Send a message.\nWe respond quickly.',
    active: 'Active',
    security_2fa: '2FA active',
    lang_label: 'Language',
    news_title: 'News',
    news_subtitle: 'Latest financial market news',
    news_loading: 'Loading news…',
    news_empty: 'No news available at the moment.',
    news_read: 'Read more',
    reg_name_ph: 'John Smith',
    reg_email_ph: 'example@gmail.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Create your free account and start investing',
    reg_terms: 'By creating an account you agree to our Terms of Service and Privacy Policy.',
    dep_title_full: 'Fund Deposit',
    dep_subtitle_full: 'Securely add funds to your EuroVault account',
    dep_card_info: 'Your payment data is encrypted with 256-bit SSL.',
    dep_confirm_btn: 'Confirm Deposit',
    dep_processing_msg: 'Processing your deposit…',
    dep_success_msg: 'Deposit submitted successfully! Our team will process it shortly.',
    dep_why_title: 'Why deposit at EuroVault?',
    dep_secure: 'Secure transaction',
    dep_fast: 'Fast processing',
    dep_support: 'Support 24/7',
    dep_min: 'Minimum €10',
    dep_amount_hint: 'Minimum amount: €10.00',
    dep_popular: 'Popular',
    dep_summary: 'Deposit Summary',
    dep_amount_label: 'Amount',
    dep_fee: 'Fee',
    dep_fee_val: 'Free',
    dep_total: 'Total to credit',
    dep_secure_badge: '100% Secure Payment · SSL 256-bit · PCI DSS',
    wd_title_full: 'Fund Withdrawal',
    wd_subtitle_full: 'Choose your withdrawal method',
    wd_tab_sepa: 'SEPA Transfer',
    wd_tab_card: 'Card Withdrawal',
    wd_sepa_info: 'SEPA Transfer (IBAN) — typical processing 1–2 business days',
    wd_note: 'Note (optional)',
    wd_note_ph: 'Reference or additional note...',
    wd_confirm: 'Confirm SEPA Transfer',
    wd_loading_btn: 'Sending...',
    wd_card_holder: 'Card Holder',
    wd_card_holder_ph: 'Name as it appears on the card',
    wd_card_number: 'Card Number',
    wd_card_number_ph: '•••• •••• •••• ••••',
    wd_card_btn: 'Request Card Withdrawal',
    wd_cb_submitted_title: 'Request Submitted!',
    wd_cb_submitted_msg: 'Your request has been registered. Our team will contact you within 2-3 business days.',
    wd_info_available: 'Available balance',
    wd_info_sepa: 'SEPA timeline',
    wd_info_sepa_val: '1-2 business days',
    wd_info_min: 'Minimum amount',
    wd_info_min_val: '€10.00',
    wd_info_fee: 'Withdrawal fee',
    wd_info_fee_val: 'Free',
    wd_info_limit: 'Daily limit',
    wd_info_no_limit: 'No limit',
    hist_no_orders: 'No orders recorded',
    hist_no_orders_sub: 'Your orders will appear here after trading.',
    // ── Extra EN keys ─────────────────────────────────────────
    login_stat_volume: 'Assets managed', login_stat_investors: 'Investors',
    login_stat_uptime: 'Uptime', login_stat_support: 'Active support',
    login_badge_live: 'MARKETS OPEN · LIVE',
    dep_processing_step2: 'Processing by financial department', dep_processing_step3: 'Credit to your EuroVault account',
    dep_badge_instant: 'Instant',
    dep_why_1: '1-2h processing', dep_why_2: '256-bit SSL encryption', dep_why_3: 'Regulated CySEC & ESMA',
    dep_why_4: 'Visa, Mastercard, Amex, Maestro', dep_why_5: '24/7 support by chat',
    dep_summary_amount: 'Amount', dep_summary_fee: 'Fee', dep_summary_free: 'Free', dep_summary_total: 'Total credit',
    dep_new: 'New Deposit', dep_success_step1: 'Request received and validated',
    dep_success_step2: 'Processing by financial department', dep_success_step3: 'Credit to your EuroVault account',
    dep_secure_text: '🔒 Encrypted transaction · SSL 256-bit · PCI DSS Certified',
    prof_saved: 'Profile updated successfully!', prof_save_btn: 'Save Changes', prof_saving_btn: 'Saving…',
    prof_member_label: 'Member since', prof_return_label: 'Total return', prof_security_label: 'Security level',
    prof_2fa_active: '2FA active', prof_personal_data: 'Personal Data', prof_fullname_ph: 'FULL NAME',
    footer_platform: 'Platform', footer_referral: 'Partners',
    footer_terms_short: 'Terms', footer_privacy_short: 'Privacy', footer_cookies_short: 'Cookies', footer_aml_short: 'AML/KYC',
    footer_help: 'Help Centre', footer_faq: 'FAQ', footer_tutorials: 'Trading Tutorials', footer_report: 'Report Issue',
    trade_market_open: '● Markets Open', trade_live: 'Live', trade_reg_badge: 'Regulated platform',
    page_not_found: 'Page not found', page_not_found_sub: 'The page you are looking for does not exist.',
    page_go_home: 'Go to Dashboard', page_go_login: 'Go to Login', page_back: 'Back',
    ref_title: 'Partner Programme', ref_copy: 'Copy', ref_copied: 'Copied!', ref_share: 'Share',
    ref_how_title: 'How It Works', ref_levels_title: 'Partner Levels', ref_levels_sub: 'Based on deposited amount',
    ref_cta: 'Deposit and Level Up',
    // ── Dashboard EN ──────────────────────────────────────────
    dash_good_morning: 'Good morning', dash_good_afternoon: 'Good afternoon', dash_good_evening: 'Good evening',
    dash_subtitle: 'Here is your account summary', dash_quick_actions: 'Quick Actions',
    dash_recent_activity: 'Recent Activity', dash_no_activity: 'No activity yet.\nStart by making a deposit.',
    dash_account_status: 'Account Status', dash_kyc_verified: '✓ Identity Verified',
    dash_kyc_verified_sub: 'Full access to the platform', dash_kyc_pending: 'KYC Pending',
    dash_kyc_pending_sub: 'Submit your documents', dash_verify_now: 'Verify Now →',
    dash_available_balance: 'Available balance', dash_go_trade: 'Markets Open',
    dash_go_trade_sub: 'Forex · Crypto · Stocks · Metals · Commodities', dash_live: 'Live',
    dash_referral: 'Partner Program', dash_referral_guests: 'Invited', dash_referral_bonus: 'Total Bonus',
    dash_see_program: 'See Full Program', dash_daily_profit: 'Daily Profit', dash_profit_not_set: 'Rate not set',
    dash_investment_goal: 'Investment Goal', dash_set_goal: 'Set Investment Goal',
    dash_set_goal_sub: 'Track progress towards your goal',
    prof_goal_title: 'Investment Goal', prof_goal_sub: 'Set a goal and track your progress',
    prof_goal_name: 'Goal Name', prof_goal_amount: 'Target Value (€)',
    prof_goal_save: 'Save Goal', prof_goal_saving: 'Saving…', prof_goal_update: 'Update', prof_goal_define: 'Set Goal',
    prof_goal_edit: 'Edit', prof_goal_cancel: 'Cancel',
    prof_sessions_title: 'Session History', prof_sessions_sub: 'Last account accesses',
    prof_sessions_empty: 'No sessions recorded yet.', prof_sessions_current: 'Current',
    prof_change_pw: 'Change Password', prof_account_summary: 'Account Summary',
    prof_member_since: 'Member since', prof_total_return: 'Total return', prof_security_level: 'Security level',
    news_realtime: 'Live', news_articles: 'articles', news_next_update: 'Next update in',
    news_refresh: 'Refresh', news_sources: 'Sources: Reuters · Yahoo Finance · CoinDesk · Investing.com',
    news_search_ph: 'Search live news...', news_no_results: 'No news found',
    bal_title: 'Balance Evolution', bal_subtitle: 'Visual history of the last 30 days',
    bal_current: 'Current Balance', bal_profit: 'Total Profit', bal_change: '30d Change',
    bal_gain: 'Absolute Gain', bal_chart_title: 'Balance Over Time', bal_history: 'Detailed History',
    bal_no_data: 'No history available yet.', bal_date: 'Date', bal_variation: 'Change',
  },

  es: {
    login_title: 'Iniciar Sesión',
    login_subtitle: 'Bienvenido. Introduzca sus credenciales de acceso.',
    login_email: 'Dirección de E-mail',
    login_email_ph: 'ejemplo@gmail.com',
    login_password: 'Contraseña',
    login_btn: 'Entrar',
    login_loading: 'Iniciando sesión…',
    login_no_account: '¿No tiene cuenta?',
    login_create: 'Crear cuenta gratuita',
    login_secure: 'Conexión segura y cifrada. Sus datos están protegidos.',
    login_hero1: 'Invierta con',
    login_hero2: 'EuroVault',
    login_desc: 'Acceda a mercados europeos y globales con una plataforma segura, regulada y centrada en sus objetivos financieros.',
    login_reg1: 'Regulado por ESMA y CySEC',
    login_reg2: 'Cifrado SSL de 256 bits',
    login_reg3: 'Operaciones en tiempo real',
    reg_title: 'Crear Cuenta',
    reg_name: 'Nombre Completo',
    reg_email: 'E-mail',
    reg_password: 'Contraseña',
    reg_country: 'País',
    reg_btn: 'Crear Cuenta',
    reg_loading: 'Creando cuenta…',
    reg_have_account: '¿Ya tiene cuenta?',
    reg_login: 'Iniciar sesión',
    nav_trade: 'Operar',
    nav_deposit: 'Depósito',
    nav_withdrawal: 'Retiro',
    nav_history: 'Historial',
    nav_news: 'Noticias',
    nav_profile: 'Perfil',
    nav_logout: 'Salir',
    nav_balance: 'Saldo',
    nav_profit: 'Beneficio',
    nav_total_balance: 'Saldo Total',
    trade_title: 'Operar',
    trade_subtitle: 'Mercados globales en tiempo real',
    trade_buy: 'COMPRAR',
    trade_sell: 'VENDER',
    trade_instrument: 'Instrumento',
    trade_amount: 'Importe (€)',
    trade_leverage: 'Apalancamiento',
    trade_direction: 'Dirección',
    trade_price: 'Precio actual',
    trade_exposure: 'Exposición',
    trade_open_btn: 'Abrir Operación',
    trade_close_btn: 'Cerrar Operación',
    trade_processing: 'Procesando…',
    trade_success_open: 'Operación abierta con éxito',
    trade_success_close: 'Operación cerrada con éxito',
    trade_invalid_amount: 'Importe no válido',
    trade_min_amount: 'Mínimo €10,00.',
    trade_order_opened: '✓ Operación Abierta',
    trade_order_closed: '✓ Operación Cerrada',
    trade_forex_quotes: 'Cotizaciones Forex',
    trade_search: 'Buscar…',
    trade_no_results: 'Sin resultados',
    trade_deposit_btn: 'Depósito',
    trade_withdrawal_btn: 'Retiro',
    trade_reg_info: 'Plataforma regulada por CySEC · MiFID II · Fondos protegidos ICF',
    dep_title: 'Depósito',
    dep_subtitle: 'Añada fondos a su cuenta',
    dep_processing: 'Procesando depósito…',
    dep_success: '¡Depósito enviado! Nuestro equipo lo procesará en breve.',
    dep_cardholder: 'Nombre del Titular',
    dep_card_number: 'Número de Tarjeta',
    dep_expiry: 'Caducidad (MM/AA)',
    dep_cvv: 'CVV',
    dep_country: 'País',
    dep_postal: 'Código Postal',
    dep_amount: 'Importe (€)',
    dep_btn: 'Depositar',
    dep_loading: 'Procesando…',
    wd_title: 'Retiro',
    wd_subtitle: 'Solicite la retirada de sus fondos',
    wd_sepa: 'Transferencia Bancaria (SEPA)',
    wd_card: 'Devolución a la Tarjeta',
    wd_holder: 'Titular de la Cuenta',
    wd_iban: 'IBAN',
    wd_bic: 'Código BIC/SWIFT',
    wd_amount: 'Importe (€)',
    wd_btn: 'Solicitar Retiro',
    wd_processing: 'Procesando…',
    wd_success: '¡Solicitud enviada con éxito!',
    profile_title: 'Mi Perfil',
    profile_subtitle: 'Gestione los datos de su cuenta',
    profile_fullname: 'Nombre Completo',
    profile_email: 'Dirección de E-mail',
    profile_phone: 'Número de Teléfono',
    profile_country: 'País de Residencia',
    profile_save: 'Guardar Cambios',
    profile_saving: 'Guardando…',
    profile_saved: '¡Perfil actualizado con éxito!',
    profile_account: 'Resumen de Cuenta',
    profile_balance: 'Saldo disponible',
    profile_profit: 'Beneficio acumulado',
    profile_status: 'Estado de la cuenta',
    profile_member: 'Miembro desde',
    profile_indicators: 'Indicadores',
    profile_return: 'Rendimiento total',
    profile_security: 'Nivel de seguridad',
    profile_change_pw: 'Cambiar Contraseña',
    kyc_title: 'Verificación de Identidad (KYC)',
    kyc_subtitle: 'Envíe su documento para activar retiros completos',
    kyc_verified: 'Verificado',
    kyc_pending: 'En revisión',
    kyc_rejected: 'Rechazado',
    kyc_doc_type: 'Tipo de Documento',
    kyc_file: 'Archivo (PDF, JPG, PNG — máx. 10 MB)',
    kyc_click: 'Haga clic para seleccionar archivo',
    kyc_uploading: 'Subiendo…',
    kyc_success: '¡Documento enviado con éxito!',
    kyc_review: 'Nuestro equipo lo revisará en breve.',
    kyc_already_sent: 'Documento ya enviado — pendiente de revisión',
    kyc_verified_msg: 'Identidad verificada con éxito',
    kyc_verified_sub: 'Su cuenta tiene acceso completo a todos los servicios.',
    kyc_bi: 'DNI / Tarjeta de Ciudadano',
    kyc_passport: 'Pasaporte',
    kyc_driver: 'Permiso de Conducir',
    kyc_proof: 'Justificante de Domicilio',
    hist_title: 'Historial de Órdenes',
    hist_subtitle: 'Todas sus operaciones registradas',
    hist_refresh: 'Actualizar',
    hist_loading: 'Cargando historial…',
    hist_empty_title: 'Ninguna operación registrada',
    hist_empty_sub: 'Sus órdenes aparecerán aquí después de operar.',
    hist_instrument: 'Instrumento',
    hist_side: 'Lado',
    hist_amount: 'Importe',
    hist_leverage: 'Apalancamiento',
    hist_exposure: 'Exposición',
    hist_price: 'Precio',
    hist_date: 'Fecha / Hora',
    hist_buy: 'Compra',
    hist_sell: 'Venta',
    footer_desc: 'Plataforma de inversión premium regulada por CySEC y MiFID II. Ofrecemos acceso a mercados globales con total transparencia.',
    footer_links: 'Enlaces Rápidos',
    footer_legal: 'Avisos Legales',
    footer_risk: 'Aviso de Riesgo',
    footer_privacy: 'Política de Privacidad',
    footer_terms: 'Términos de Servicio',
    footer_aml: 'Política AML/KYC',
    footer_contact: 'Contacto',
    footer_support: 'Soporte',
    footer_rights: 'Todos los derechos reservados.',
    footer_risk_text: 'Los CFDs son instrumentos complejos y conllevan un alto riesgo de pérdida rápida de dinero. Asegúrese de entender cómo funcionan los CFDs antes de invertir.',
    footer_reg: 'Regulado CySEC Lic. nº 409/22 · MiFID II · ICF',
    chat_support: 'Soporte EuroVault',
    chat_online: '● En línea',
    chat_placeholder: 'Escriba un mensaje…',
    chat_send: 'Enviar',
    chat_empty: 'Envíe un mensaje.\nRespondemos rápido.',
    active: 'Activa',
    security_2fa: '2FA activo',
    lang_label: 'Idioma',
    news_title: 'Noticias',
    news_subtitle: 'Últimas noticias de los mercados financieros',
    news_loading: 'Cargando noticias…',
    news_empty: 'Sin noticias disponibles por el momento.',
    news_read: 'Leer más',
    reg_name_ph: 'Juan García',
    reg_email_ph: 'ejemplo@gmail.com',
    reg_password_ph: '••••••••',
    reg_subtitle: 'Cree su cuenta gratuita y comience a invertir',
    reg_terms: 'Al crear una cuenta acepta nuestros Términos de Servicio y Política de Privacidad.',
    dep_title_full: 'Depósito de Fondos',
    dep_subtitle_full: 'Añada fondos de forma segura a su cuenta EuroVault',
    dep_card_info: 'Sus datos de pago están cifrados con SSL de 256 bits.',
    dep_confirm_btn: 'Confirmar Depósito',
    dep_processing_msg: 'Procesando su depósito…',
    dep_success_msg: '¡Depósito enviado con éxito! Nuestro equipo lo procesará en breve.',
    dep_why_title: '¿Por qué depositar en EuroVault?',
    dep_secure: 'Transacción segura',
    dep_fast: 'Procesamiento rápido',
    dep_support: 'Soporte 24/7',
    dep_min: 'Mínimo €10',
    dep_amount_hint: 'Importe mínimo: €10,00',
    dep_popular: 'Popular',
    dep_summary: 'Resumen del Depósito',
    dep_amount_label: 'Importe',
    dep_fee: 'Tarifa',
    dep_fee_val: 'Gratis',
    dep_total: 'Total a acreditar',
    dep_secure_badge: 'Pago 100% Seguro · SSL 256-bit · PCI DSS',
    wd_title_full: 'Retiro de Fondos',
    wd_subtitle_full: 'Elija su método de retiro',
    wd_tab_sepa: 'Transferencia SEPA',
    wd_tab_card: 'Retiro a Tarjeta',
    wd_sepa_info: 'Transferencia SEPA (IBAN) — plazo típico 1–2 días hábiles',
    wd_note: 'Nota (opcional)',
    wd_note_ph: 'Referencia o nota adicional...',
    wd_confirm: 'Confirmar Transferencia SEPA',
    wd_loading_btn: 'Enviando...',
    wd_card_holder: 'Titular de la Tarjeta',
    wd_card_holder_ph: 'Nombre como aparece en la tarjeta',
    wd_card_number: 'Número de Tarjeta',
    wd_card_number_ph: '•••• •••• •••• ••••',
    wd_card_btn: 'Solicitar Retiro a Tarjeta',
    wd_cb_submitted_title: '¡Solicitud Enviada!',
    wd_cb_submitted_msg: 'Su solicitud ha sido registrada. Nuestro equipo le contactará en 2-3 días hábiles.',
    wd_info_available: 'Saldo disponible',
    wd_info_sepa: 'Plazo SEPA',
    wd_info_sepa_val: '1-2 días hábiles',
    wd_info_min: 'Importe mínimo',
    wd_info_min_val: '€10,00',
    wd_info_fee: 'Tarifa de retiro',
    wd_info_fee_val: 'Gratis',
    wd_info_limit: 'Límite diario',
    wd_info_no_limit: 'Sin límite',
    hist_no_orders: 'Ninguna operación registrada',
    hist_no_orders_sub: 'Sus órdenes aparecerán aquí después de operar.',
    // ── Extra ES keys ─────────────────────────────────────────
    login_stat_volume: 'Activos gestionados', login_stat_investors: 'Inversores',
    login_stat_uptime: 'Uptime', login_stat_support: 'Soporte activo',
    login_badge_live: 'MERCADOS ABIERTOS · EN VIVO',
    dep_processing_step2: 'Procesamiento por el departamento financiero', dep_processing_step3: 'Crédito en su cuenta EuroVault',
    dep_badge_instant: 'Instant',
    dep_why_1: 'Procesamiento en 1-2h', dep_why_2: 'Cifrado SSL 256-bit', dep_why_3: 'Regulado CySEC & ESMA',
    dep_why_4: 'Visa, Mastercard, Amex, Maestro', dep_why_5: 'Soporte 24/7 por chat',
    dep_summary_amount: 'Importe', dep_summary_fee: 'Tarifa', dep_summary_free: 'Gratis', dep_summary_total: 'Total acreditado',
    dep_new: 'Nuevo Depósito', dep_success_step1: 'Solicitud recibida y validada',
    dep_success_step2: 'Procesamiento por el departamento financiero', dep_success_step3: 'Crédito en su cuenta EuroVault',
    dep_secure_text: '🔒 Transacción cifrada · SSL 256-bit · PCI DSS Certificado',
    prof_saved: '¡Perfil actualizado con éxito!', prof_save_btn: 'Guardar Cambios', prof_saving_btn: 'Guardando…',
    prof_member_label: 'Miembro desde', prof_return_label: 'Rendimiento total', prof_security_label: 'Nivel de seguridad',
    prof_2fa_active: '2FA activo', prof_personal_data: 'Datos Personales', prof_fullname_ph: 'NOMBRE COMPLETO',
    footer_platform: 'Plataforma', footer_referral: 'Socios',
    footer_terms_short: 'Términos', footer_privacy_short: 'Privacidad', footer_cookies_short: 'Cookies', footer_aml_short: 'AML/KYC',
    footer_help: 'Centro de Ayuda', footer_faq: 'FAQ', footer_tutorials: 'Tutoriales', footer_report: 'Reportar Problema',
    trade_market_open: '● Mercados Abiertos', trade_live: 'En vivo', trade_reg_badge: 'Plataforma regulada',
    page_not_found: 'Página no encontrada', page_not_found_sub: 'La página que busca no existe o fue movida.',
    page_go_home: 'Ir al Dashboard', page_go_login: 'Ir al Login', page_back: 'Volver',
    ref_title: 'Programa de Socios', ref_copy: 'Copiar', ref_copied: '¡Copiado!', ref_share: 'Compartir',
    ref_how_title: 'Cómo Funciona', ref_levels_title: 'Niveles de Socio', ref_levels_sub: 'Basado en el importe depositado',
    ref_cta: 'Depositar y Subir de Nivel',
    // ── Dashboard ES ──────────────────────────────────────────
    dash_good_morning: 'Buenos días', dash_good_afternoon: 'Buenas tardes', dash_good_evening: 'Buenas noches',
    dash_subtitle: 'Aquí está el resumen de su cuenta', dash_quick_actions: 'Acciones Rápidas',
    dash_recent_activity: 'Actividades Recientes', dash_no_activity: 'Sin actividades aún.\nEmpiece por hacer un depósito.',
    dash_account_status: 'Estado de la Cuenta', dash_kyc_verified: '✓ Identidad Verificada',
    dash_kyc_verified_sub: 'Acceso completo a la plataforma', dash_kyc_pending: 'KYC Pendiente',
    dash_kyc_pending_sub: 'Envíe sus documentos', dash_verify_now: 'Verificar Ahora →',
    dash_available_balance: 'Saldo disponible', dash_go_trade: 'Mercados Abiertos',
    dash_go_trade_sub: 'Forex · Cripto · Acciones · Metales · Materias primas', dash_live: 'En vivo',
    dash_referral: 'Programa de Socios', dash_referral_guests: 'Invitados', dash_referral_bonus: 'Bono Total',
    dash_see_program: 'Ver Programa Completo', dash_daily_profit: 'Beneficio Diario', dash_profit_not_set: 'Tasa no definida',
    dash_investment_goal: 'Meta de Inversión', dash_set_goal: 'Establecer Meta de Inversión',
    dash_set_goal_sub: 'Siga el progreso hacia su objetivo',
    prof_goal_title: 'Meta de Inversión', prof_goal_sub: 'Establezca un objetivo y siga el progreso',
    prof_goal_name: 'Nombre de la Meta', prof_goal_amount: 'Valor Objetivo (€)',
    prof_goal_save: 'Guardar Meta', prof_goal_saving: 'Guardando…', prof_goal_update: 'Actualizar', prof_goal_define: 'Definir Meta',
    prof_goal_edit: 'Editar', prof_goal_cancel: 'Cancelar',
    prof_sessions_title: 'Historial de Sesiones', prof_sessions_sub: 'Últimos accesos a su cuenta',
    prof_sessions_empty: 'Sin sesiones registradas aún.', prof_sessions_current: 'Actual',
    prof_change_pw: 'Cambiar Contraseña', prof_account_summary: 'Resumen de Cuenta',
    prof_member_since: 'Miembro desde', prof_total_return: 'Rendimiento total', prof_security_level: 'Nivel de seguridad',
    news_realtime: 'Tiempo real', news_articles: 'artículos', news_next_update: 'Próxima actualización en',
    news_refresh: 'Actualizar', news_sources: 'Fuentes: Reuters · Yahoo Finance · CoinDesk · Investing.com',
    news_search_ph: 'Buscar noticias en tiempo real...', news_no_results: 'No se encontraron noticias',
    bal_title: 'Evolución del Saldo', bal_subtitle: 'Historial visual de los últimos 30 días',
    bal_current: 'Saldo Actual', bal_profit: 'Beneficio Total', bal_change: 'Cambio 30d',
    bal_gain: 'Ganancia Absoluta', bal_chart_title: 'Saldo a lo Largo del Tiempo', bal_history: 'Historial Detallado',
    bal_no_data: 'Sin historial disponible aún.', bal_date: 'Fecha', bal_variation: 'Variación',
  },
};

// ─────────────────────────────────────────────────────────────
//  Contexto
// ─────────────────────────────────────────────────────────────
const LangContext = createContext(null);

// Detectar idioma do navegador automaticamente
function detectBrowserLang() {
  const saved = localStorage.getItem('ev_lang');
  if (saved && ['pt', 'en', 'es'].includes(saved)) return saved;
  // Ler idioma do navegador
  const raw = (navigator.language || navigator.languages?.[0] || 'pt').toLowerCase();
  if (raw.startsWith('es')) return 'es';
  if (raw.startsWith('en')) return 'en';
  if (raw.startsWith('pt')) return 'pt';
  // Para outros idiomas europeus, usar inglês como fallback
  return 'en';
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => detectBrowserLang());

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('ev_lang', newLang);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['pt']?.[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
